//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class arzyzbi6_value
    {
        public long ID { get; set; }
        public Nullable<long> FK_doreh { get; set; }
        public Nullable<long> FK_soal { get; set; }
        public Nullable<long> FK_gozeneh { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public string FULL_namesabt { get; set; }
        public string cod_personaly { get; set; }
        public string semat { get; set; }
        public Nullable<System.DateTime> datatime { get; set; }
        public Nullable<int> FK_usr_sabt { get; set; }
        public Nullable<long> vaznsoal { get; set; }
        public Nullable<bool> Active { get; set; }
        public string sharhsoal { get; set; }
    
        public virtual arzyzbi2_soal arzyzbi2_soal { get; set; }
        public virtual arzyzbi5_time arzyzbi5_time { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
