//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class arzyzbi7_value_usr
    {
        public long ID { get; set; }
        public Nullable<long> FK_Doreh { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public string job { get; set; }
        public string tahsilat { get; set; }
        public string sabgheh_job { get; set; }
        public string phon_number { get; set; }
        public Nullable<int> usr_sabt { get; set; }
        public string Full_namesabt { get; set; }
        public Nullable<bool> Actuve { get; set; }
        public Nullable<System.DateTime> datatme_sabt { get; set; }
        public Nullable<int> sokonat { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
