//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class arzyzbi2_soal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arzyzbi2_soal()
        {
            this.arzyzbi3_gozeneh = new HashSet<arzyzbi3_gozeneh>();
            this.arzyzbi6_value = new HashSet<arzyzbi6_value>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_arzyzbi1 { get; set; }
        public string soal { get; set; }
        public string sharh { get; set; }
        public Nullable<System.DateTime> datatime { get; set; }
        public Nullable<int> usrsabt { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> vazn { get; set; }
    
        public virtual arzyzbi1 arzyzbi1 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi3_gozeneh> arzyzbi3_gozeneh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi6_value> arzyzbi6_value { get; set; }
    }
}
