//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class arzyzbi3_gozeneh
    {
        public long ID { get; set; }
        public long FK_arzyabisoal { get; set; }
        public string gozineh { get; set; }
        public Nullable<long> vazn { get; set; }
        public Nullable<System.DateTime> datatime { get; set; }
        public Nullable<int> usrsabt { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual arzyzbi2_soal arzyzbi2_soal { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
