//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class arzyzbi8_edit
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<long> FK_name { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<int> vazsoal1 { get; set; }
        public Nullable<int> vazsoal2 { get; set; }
        public Nullable<int> vazsoal3 { get; set; }
        public Nullable<int> vazsoal4 { get; set; }
        public Nullable<int> codmaneh { get; set; }
        public Nullable<int> edittelephon { get; set; }
        public Nullable<long> mablagh_vosoli { get; set; }
        public Nullable<int> kilovat { get; set; }
        public Nullable<long> mablagh4kilovat { get; set; }
        public Nullable<long> vaziatshomareh { get; set; }
        public string shomareh { get; set; }
        public string sharh { get; set; }
        public Nullable<System.DateTime> datatimesabt { get; set; }
        public Nullable<int> usrsabt { get; set; }
        public Nullable<int> codepersanalysabt { get; set; }
        public string fullnamesabt { get; set; }
        public string shomareh2 { get; set; }
        public Nullable<int> mantagheh { get; set; }
        public Nullable<int> rozkar { get; set; }
        public Nullable<int> vazsoal5 { get; set; }
        public string shomareh3 { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
