//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class arzyzbi1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arzyzbi1()
        {
            this.arzyzbi2_soal = new HashSet<arzyzbi2_soal>();
            this.arzyzbi4_link = new HashSet<arzyzbi4_link>();
            this.arzyzbi5_time = new HashSet<arzyzbi5_time>();
        }
    
        public long ID { get; set; }
        public string name { get; set; }
        public Nullable<int> shomareh { get; set; }
        public Nullable<System.DateTime> datatime { get; set; }
        public Nullable<int> usrsabt { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> typegozaresh { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi2_soal> arzyzbi2_soal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi4_link> arzyzbi4_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi5_time> arzyzbi5_time { get; set; }
    }
}
