//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class arzyzbi5_time
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arzyzbi5_time()
        {
            this.arzyzbi6_value = new HashSet<arzyzbi6_value>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_arzyzbi1 { get; set; }
        public Nullable<System.DateTime> datastart { get; set; }
        public Nullable<System.DateTime> dataend { get; set; }
        public Nullable<System.DateTime> datatimesabt { get; set; }
        public string namedoreh { get; set; }
        public Nullable<int> usr_sabt { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual arzyzbi1 arzyzbi1 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi6_value> arzyzbi6_value { get; set; }
    }
}
