//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaleLinkRequests
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public string LinkCode { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime ExpiresAt { get; set; }
        public Nullable<System.DateTime> UsedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
