//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityPriority
    {
        public long ID { get; set; }
        public string city_name { get; set; }
        public Nullable<int> day_number { get; set; }
        public Nullable<int> priority { get; set; }
    }
}
