//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class closed_time_estedad
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<System.DateTime> timeend { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
