//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlVersions
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Decription { get; set; }
        public Nullable<int> fk_tbUsers { get; set; }
        public System.DateTime Date { get; set; }
        public string FileName { get; set; }
        public bool InUsed { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
