//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class countnero_1218_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public countnero_1218_1()
        {
            this.countnero_1218_2 = new HashSet<countnero_1218_2>();
            this.countnero_1218_4 = new HashSet<countnero_1218_4>();
            this.countnero_1218_5 = new HashSet<countnero_1218_5>();
        }
    
        public long ID { get; set; }
        public string namcity { get; set; }
        public string mantaghej { get; set; }
        public Nullable<long> kodmantageh { get; set; }
        public Nullable<long> kodsamaneh { get; set; }
        public Nullable<long> vaziat { get; set; }
        public string sharh { get; set; }
        public Nullable<long> FK_gozaresh { get; set; }
    
        public virtual countnero_1218_0 countnero_1218_0 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<countnero_1218_2> countnero_1218_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<countnero_1218_4> countnero_1218_4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<countnero_1218_5> countnero_1218_5 { get; set; }
    }
}
