//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class countnero_1218_5
    {
        public long ID { get; set; }
        public Nullable<long> Fk_gozaresh { get; set; }
        public Nullable<long> Fk_city { get; set; }
        public Nullable<long> Count { get; set; }
        public Nullable<long> Meghdar { get; set; }
        public string name { get; set; }
        public string name2 { get; set; }
        public Nullable<double> darsad { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> yaer { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<long> Had_vosol_shodeh_kol { get; set; }
        public Nullable<long> Had_entezar_kol { get; set; }
        public Nullable<long> Had_entezar_inday { get; set; }
        public Nullable<long> Had_vosol_shodeh_day { get; set; }
    
        public virtual countnero_1218_0 countnero_1218_0 { get; set; }
        public virtual countnero_1218_1 countnero_1218_1 { get; set; }
    }
}
