//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class countnero_1218_3
    {
        public long ID { get; set; }
        public Nullable<long> FK_nero { get; set; }
        public Nullable<long> FK_count2 { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<long> valubig { get; set; }
        public Nullable<long> active { get; set; }
    }
}
