//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class countnero_1218_2
    {
        public long ID { get; set; }
        public Nullable<long> FK_nero { get; set; }
        public string name { get; set; }
        public Nullable<long> saghf { get; set; }
        public Nullable<long> FK_gozaresh { get; set; }
    
        public virtual countnero_1218_0 countnero_1218_0 { get; set; }
        public virtual countnero_1218_1 countnero_1218_1 { get; set; }
    }
}
