//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class countnero_1218_4
    {
        public long ID { get; set; }
        public Nullable<long> FK_city { get; set; }
        public Nullable<long> count { get; set; }
        public Nullable<long> cod { get; set; }
        public Nullable<long> cod2 { get; set; }
        public Nullable<long> active { get; set; }
    
        public virtual countnero_1218_1 countnero_1218_1 { get; set; }
    }
}
