//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_linkjobname_5
    {
        public long ID { get; set; }
        public Nullable<long> FK_Linkjob { get; set; }
        public string name { get; set; }
        public Nullable<int> vaziat { get; set; }
    
        public virtual Create_job_1 Create_job_1 { get; set; }
    }
}
