//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_linkjob_2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Create_linkjob_2()
        {
            this.Create_linkrelation2job_3 = new HashSet<Create_linkrelation2job_3>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_job { get; set; }
        public string name { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> FK_city { get; set; }
        public Nullable<bool> del { get; set; }
    
        public virtual Create_job_1 Create_job_1 { get; set; }
        public virtual tbCities tbCities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Create_linkrelation2job_3> Create_linkrelation2job_3 { get; set; }
    }
}
