//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_linkmamorjob_4
    {
        public long ID { get; set; }
        public Nullable<long> FK_link { get; set; }
        public string unic { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public string valueamal { get; set; }
        public Nullable<int> FK_moalfeh { get; set; }
        public Nullable<System.DateTime> TIMESABT { get; set; }
        public string timesabtsahmsi { get; set; }
        public Nullable<int> FK_usrsabt { get; set; }
        public Nullable<int> personalIDsabt { get; set; }
        public string Fullnamesabt { get; set; }
        public string cityname { get; set; }
        public Nullable<int> fk_city { get; set; }
    
        public virtual Create_linkrelation2job_3 Create_linkrelation2job_3 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
