//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_realjob2_2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Create_realjob2_2()
        {
            this.Create_linkrelation4detailjob_4 = new HashSet<Create_linkrelation4detailjob_4>();
        }
    
        public long ID { get; set; }
        public string nam { get; set; }
        public Nullable<long> FK_Create_linkjob_2 { get; set; }
        public Nullable<int> vaziat { get; set; }
    
        public virtual Create_job_1 Create_job_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Create_linkrelation4detailjob_4> Create_linkrelation4detailjob_4 { get; set; }
    }
}
