//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crete_job__erja_1
    {
        public long ID { get; set; }
        public string namejob { get; set; }
        public Nullable<int> vaziat { get; set; }
        public string shomareh { get; set; }
        public Nullable<long> SHMAREHINT { get; set; }
    }
}
