//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashbord_talafat
    {
        public long ID { get; set; }
        public Nullable<int> FK_usrsabt { get; set; }
        public Nullable<System.DateTime> astarigh { get; set; }
        public Nullable<System.DateTime> tatarigh { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> yaer { get; set; }
        public Nullable<int> day { get; set; }
        public string city { get; set; }
        public Nullable<long> sum { get; set; }
        public string sum_n { get; set; }
        public Nullable<double> avrage { get; set; }
        public string avrage_n { get; set; }
        public string value { get; set; }
        public Nullable<double> vali_bi { get; set; }
        public Nullable<long> code { get; set; }
        public Nullable<int> vaz { get; set; }
        public string sharh { get; set; }
        public string malfej { get; set; }
    }
}
