//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_usr_Dastresi
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<long> page_number { get; set; }
        public string name_page { get; set; }
        public Nullable<int> vaziat_page { get; set; }
        public Nullable<int> vazziat_fkusr { get; set; }
        public string title { get; set; }
    }
}
