//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadcratname
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbAsnadcratname()
        {
            this.dbAsnadcratasnadrelatin = new HashSet<dbAsnadcratasnadrelatin>();
            this.dbAsnadcratname1 = new HashSet<dbAsnadcratname>();
        }
    
        public long ID { get; set; }
        public string name { get; set; }
        public Nullable<double> nergh { get; set; }
        public string merghname { get; set; }
        public Nullable<int> nerghnintlink { get; set; }
        public string codmahsol { get; set; }
        public Nullable<long> IDre { get; set; }
        public Nullable<long> FK_PK_dbAsnadDastehband2 { get; set; }
    
        public virtual tbUnitParameter tbUnitParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadcratasnadrelatin> dbAsnadcratasnadrelatin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadcratname> dbAsnadcratname1 { get; set; }
        public virtual dbAsnadcratname dbAsnadcratname2 { get; set; }
        public virtual dbAsnadDastehband2 dbAsnadDastehband2 { get; set; }
    }
}
