//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadcratsher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbAsnadcratsher()
        {
            this.dbAsnadcratasnad = new HashSet<dbAsnadcratasnad>();
        }
    
        public long ID { get; set; }
        public string nameshr { get; set; }
        public Nullable<long> codeghtesadi { get; set; }
        public string addres { get; set; }
        public string codmoadyan { get; set; }
        public string MOBILEPHON { get; set; }
        public string SABETPHONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadcratasnad> dbAsnadcratasnad { get; set; }
    }
}
