//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadCheack3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbAsnadCheack3()
        {
            this.dbAsnadCheack4 = new HashSet<dbAsnadCheack4>();
            this.dbAsnadCheack6 = new HashSet<dbAsnadCheack6>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_dbAsnadCheack2 { get; set; }
        public string SJOMERH_seryal { get; set; }
        public Nullable<int> COunt_Barg { get; set; }
        public string Shanasehsayadi { get; set; }
    
        public virtual dbAsnadCheack2 dbAsnadCheack2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadCheack4> dbAsnadCheack4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadCheack6> dbAsnadCheack6 { get; set; }
    }
}
