//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnaduplaodfil1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbAsnaduplaodfil1()
        {
            this.dbAsnaduplaodfil11 = new HashSet<dbAsnaduplaodfil1>();
            this.dbAsnaduplaodfil2 = new HashSet<dbAsnaduplaodfil2>();
        }
    
        public long ID { get; set; }
        public string name { get; set; }
        public string merghname { get; set; }
        public Nullable<int> nerghnintlink { get; set; }
        public string codmahsol { get; set; }
        public Nullable<long> IDre { get; set; }
        public Nullable<double> nergh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnaduplaodfil1> dbAsnaduplaodfil11 { get; set; }
        public virtual dbAsnaduplaodfil1 dbAsnaduplaodfil12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnaduplaodfil2> dbAsnaduplaodfil2 { get; set; }
    }
}
