//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadtress1
    {
        public int ID { get; set; }
        public Nullable<long> marhaleh { get; set; }
        public Nullable<long> ragham { get; set; }
        public Nullable<long> start { get; set; }
    }
}
