//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadcratasnad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbAsnadcratasnad()
        {
            this.dbAsnadcratasnadrelatin = new HashSet<dbAsnadcratasnadrelatin>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_name { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<double> sum { get; set; }
        public string titel { get; set; }
        public string File_RealName { get; set; }
        public string File_SystemName { get; set; }
        public string sumstring { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public string codsamanehmoadyan { get; set; }
        public string sanadmalyy { get; set; }
        public string shomarehfactor { get; set; }
        public Nullable<long> pardaght { get; set; }
        public string numberpagery { get; set; }
        public Nullable<System.DateTime> datausr { get; set; }
        public Nullable<int> FKusr_sabt { get; set; }
        public Nullable<System.DateTime> datatimesabt { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<bool> taeed { get; set; }
        public string Factor { get; set; }
    
        public virtual dbAsnadcratsher dbAsnadcratsher { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadcratasnadrelatin> dbAsnadcratasnadrelatin { get; set; }
    }
}
