//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadCheack6
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Datatime { get; set; }
        public Nullable<long> FK_dbAsnadCheack5 { get; set; }
        public Nullable<long> FK_dbAsnadCheack3 { get; set; }
        public string sharh { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual dbAsnadCheack3 dbAsnadCheack3 { get; set; }
        public virtual dbAsnadCheack5 dbAsnadCheack5 { get; set; }
    }
}
