//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadDastehband2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbAsnadDastehband2()
        {
            this.dbAsnadcratname = new HashSet<dbAsnadcratname>();
        }
    
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> FK_HOGHOGHI { get; set; }
        public string Titrl { get; set; }
        public Nullable<long> COD { get; set; }
        public Nullable<long> FK_dbAsnadDastehband1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadcratname> dbAsnadcratname { get; set; }
        public virtual dbAsnadDastehband1 dbAsnadDastehband1 { get; set; }
        public virtual tbCompanies tbCompanies { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
