//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnaduplaodfil2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbAsnaduplaodfil2()
        {
            this.dbAsnaduplaodfil3 = new HashSet<dbAsnaduplaodfil3>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_NAME { get; set; }
        public Nullable<bool> defaultRadio1 { get; set; }
        public Nullable<bool> defaultRadio2 { get; set; }
        public Nullable<bool> defaultRadio3 { get; set; }
        public Nullable<bool> defaultRadio4 { get; set; }
        public Nullable<bool> defaultRadio5 { get; set; }
        public Nullable<bool> defaultRadio6 { get; set; }
        public Nullable<bool> defaultRadio7 { get; set; }
        public Nullable<int> value_name { get; set; }
        public Nullable<int> value_value { get; set; }
        public Nullable<bool> DAyChecked { get; set; }
        public Nullable<bool> shomarehnameh { get; set; }
        public Nullable<bool> timestartChecked { get; set; }
        public Nullable<bool> timeendChecked { get; set; }
        public Nullable<bool> timerepetChecked { get; set; }
        public Nullable<bool> timetamdidChecked { get; set; }
        public Nullable<bool> mablaghChecked { get; set; }
        public Nullable<bool> mozohChecked { get; set; }
        public Nullable<bool> day { get; set; }
    
        public virtual dbAsnaduplaodfil1 dbAsnaduplaodfil1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnaduplaodfil3> dbAsnaduplaodfil3 { get; set; }
    }
}
