//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadshomrehsanad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbAsnadshomrehsanad()
        {
            this.dbAsnafsherkatsanad = new HashSet<dbAsnafsherkatsanad>();
        }
    
        public int ID { get; set; }
        public string shomarehsanad { get; set; }
        public string File_RealName { get; set; }
        public string File_SystemName { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> month { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnafsherkatsanad> dbAsnafsherkatsanad { get; set; }
    }
}
