//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadCheack4
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> FK_company { get; set; }
        public Nullable<System.DateTime> Data_time { get; set; }
        public Nullable<System.DateTime> Data_time2 { get; set; }
        public string sharh { get; set; }
        public Nullable<long> FK_dbAsnadCheack3 { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<long> ID_ID { get; set; }
    
        public virtual dbAsnadCheack3 dbAsnadCheack3 { get; set; }
        public virtual tbCompanies tbCompanies { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
