//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnafsherkatsanad
    {
        public int ID { get; set; }
        public Nullable<int> numbershomareh { get; set; }
        public Nullable<double> bestankar { get; set; }
        public Nullable<double> bedehkar { get; set; }
        public Nullable<int> FK_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Titel { get; set; }
        public Nullable<long> nahei { get; set; }
        public string File_RealName { get; set; }
        public string File_SystemName { get; set; }
        public Nullable<int> FK_shmoareh { get; set; }
    
        public virtual dbAsnadshomrehsanad dbAsnadshomrehsanad { get; set; }
    }
}
