//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadcratasnadrelatin
    {
        public int ID { get; set; }
        public Nullable<long> FK_nameshr { get; set; }
        public Nullable<long> FK_namevasel { get; set; }
        public Nullable<double> count { get; set; }
        public Nullable<double> vahd { get; set; }
        public Nullable<double> megdar { get; set; }
        public Nullable<long> magdarbig { get; set; }
        public Nullable<long> FK_asliasnad { get; set; }
        public Nullable<long> taghfif { get; set; }
        public Nullable<long> bytaghfif { get; set; }
        public Nullable<long> arzish { get; set; }
        public Nullable<long> nahaei { get; set; }
        public string sharhtaghfif { get; set; }
        public string sharharzesh { get; set; }
    
        public virtual dbAsnadcratasnad dbAsnadcratasnad { get; set; }
        public virtual dbAsnadcratname dbAsnadcratname { get; set; }
    }
}
