//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadsalvorodi
    {
        public int ID { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<System.DateTime> tim { get; set; }
        public Nullable<bool> login { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
