//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbAsnadCheack2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbAsnadCheack2()
        {
            this.dbAsnadCheack3 = new HashSet<dbAsnadCheack3>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public string shomarehhesab { get; set; }
        public string SHomarehkart { get; set; }
        public string SHomarehshaba { get; set; }
        public Nullable<long> FK_dbAsnadCheack1 { get; set; }
    
        public virtual dbAsnadCheack1 dbAsnadCheack1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadCheack3> dbAsnadCheack3 { get; set; }
    }
}
