//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbdashbord1_link
    {
        public long ID { get; set; }
        public string name { get; set; }
        public string name_1 { get; set; }
        public Nullable<long> vaziat { get; set; }
        public Nullable<long> nobat { get; set; }
        public Nullable<System.DateTime> time_sabt { get; set; }
        public Nullable<long> FK_li { get; set; }
        public string name_2 { get; set; }
    }
}
