//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbdashbordmamor
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public string city { get; set; }
        public Nullable<int> job1 { get; set; }
        public Nullable<double> job2 { get; set; }
        public Nullable<double> job3 { get; set; }
        public Nullable<double> job4 { get; set; }
        public Nullable<double> job5 { get; set; }
        public Nullable<double> job6 { get; set; }
        public Nullable<double> job7 { get; set; }
        public Nullable<double> job8 { get; set; }
        public Nullable<double> job9 { get; set; }
        public Nullable<double> job10 { get; set; }
        public Nullable<double> job11 { get; set; }
        public Nullable<double> valu { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string startshamsi { get; set; }
        public string endtimesham { get; set; }
        public Nullable<int> actibe { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public string jobname { get; set; }
        public string sharh { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
