//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbdashbord1
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public string astargh_shams { get; set; }
        public string tatarigh_shams { get; set; }
        public Nullable<System.DateTime> tatarigh { get; set; }
        public Nullable<System.DateTime> astarigh { get; set; }
        public Nullable<System.DateTime> time_sabt { get; set; }
        public string name_city { get; set; }
        public string vorodi1 { get; set; }
        public string vorodi2 { get; set; }
        public string vorodi3 { get; set; }
        public string vahd { get; set; }
        public string margah { get; set; }
        public Nullable<long> sumkol { get; set; }
        public Nullable<double> avrage { get; set; }
        public Nullable<long> valu_big { get; set; }
        public string value_nv { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
