//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergha6
    {
        public long ID { get; set; }
        public string parvande { get; set; }
        public string shenaseh { get; set; }
        public Nullable<long> mablagh { get; set; }
        public string mablagh2 { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> yaer { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> vaz { get; set; }
        public string Fullname_sabt { get; set; }
        public Nullable<int> FK_usr_dabt { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public Nullable<int> vaziiat { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
