//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergha2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbergha2()
        {
            this.dberganametanble2_2 = new HashSet<dberganametanble2_2>();
            this.dbergapishghan = new HashSet<dbergapishghan>();
            this.dbergharel2_3 = new HashSet<dbergharel2_3>();
            this.dbergharel4_5 = new HashSet<dbergharel4_5>();
            this.dbergharelimsertfk1_7_1218_bace = new HashSet<dbergharelimsertfk1_7_1218_bace>();
            this.dbergharelimsertfk1_7_1218 = new HashSet<dbergharelimsertfk1_7_1218>();
            this.dbergharelimsertfk1_7 = new HashSet<dbergharelimsertfk1_7>();
            this.dbergharelimsertfk1_7_GIS = new HashSet<dbergharelimsertfk1_7_GIS>();
            this.erja_omomi = new HashSet<erja_omomi>();
            this.olaviat_1218_link = new HashSet<olaviat_1218_link>();
            this.olaviat_1218_link_olaviat = new HashSet<olaviat_1218_link_olaviat>();
            this.olaviat_1218_link_olaviat1 = new HashSet<olaviat_1218_link_olaviat>();
            this.olaviat_1218_link_shart = new HashSet<olaviat_1218_link_shart>();
            this.olaviat_1218_link_shart1 = new HashSet<olaviat_1218_link_shart>();
        }
    
        public long ID { get; set; }
        public string name { get; set; }
        public Nullable<double> vazn { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<bool> unic { get; set; }
        public Nullable<int> FK_usrsabt { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public string macAdress { get; set; }
        public Nullable<bool> del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dberganametanble2_2> dberganametanble2_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergapishghan> dbergapishghan { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharel2_3> dbergharel2_3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharel4_5> dbergharel4_5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelimsertfk1_7_1218_bace> dbergharelimsertfk1_7_1218_bace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelimsertfk1_7_1218> dbergharelimsertfk1_7_1218 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelimsertfk1_7> dbergharelimsertfk1_7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelimsertfk1_7_GIS> dbergharelimsertfk1_7_GIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erja_omomi> erja_omomi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link> olaviat_1218_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link_olaviat> olaviat_1218_link_olaviat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link_olaviat> olaviat_1218_link_olaviat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link_shart> olaviat_1218_link_shart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link_shart> olaviat_1218_link_shart1 { get; set; }
    }
}
