//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharel4_5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbergharel4_5()
        {
            this.dbergapishghan = new HashSet<dbergapishghan>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_dbergharel4 { get; set; }
        public Nullable<long> shomareh { get; set; }
        public Nullable<long> FK_dbergharel2 { get; set; }
        public string onvan { get; set; }
        public Nullable<int> FK_usrsabt { get; set; }
        public string macAdress { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public Nullable<bool> del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergapishghan> dbergapishghan { get; set; }
        public virtual dbergha2 dbergha2 { get; set; }
        public virtual dbergharel_4 dbergharel_4 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
