//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharelicrarelaton11_12
    {
        public long ID { get; set; }
        public Nullable<long> FK_db11 { get; set; }
        public Nullable<int> pardaght { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string timedata { get; set; }
        public Nullable<long> bedhi { get; set; }
        public Nullable<int> bateh { get; set; }
        public Nullable<int> enshab { get; set; }
        public Nullable<int> enshabghat { get; set; }
        public Nullable<int> moghayratfaz { get; set; }
        public Nullable<int> dastkarikontorint { get; set; }
        public Nullable<int> gharab { get; set; }
        public Nullable<int> notmogaz { get; set; }
        public string phone { get; set; }
        public Nullable<int> ghalamoftadeh { get; set; }
        public Nullable<int> vaziat { get; set; }
    
        public virtual dbergharelicratgrouprel11 dbergharelicratgrouprel11 { get; set; }
    }
}
