//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharel_4_4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbergharel_4_4()
        {
            this.dbergharel_4 = new HashSet<dbergharel_4>();
            this.olaviat_1218_link = new HashSet<olaviat_1218_link>();
            this.olaviat_1218_link_olaviat = new HashSet<olaviat_1218_link_olaviat>();
            this.olaviat_1218_link_olaviat1 = new HashSet<olaviat_1218_link_olaviat>();
            this.olaviat_1218_link_shart = new HashSet<olaviat_1218_link_shart>();
            this.olaviat_1218_link_shart1 = new HashSet<olaviat_1218_link_shart>();
        }
    
        public long ID { get; set; }
        public string name { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharel_4> dbergharel_4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link> olaviat_1218_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link_olaviat> olaviat_1218_link_olaviat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link_olaviat> olaviat_1218_link_olaviat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link_shart> olaviat_1218_link_shart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link_shart> olaviat_1218_link_shart1 { get; set; }
    }
}
