//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharel_4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbergharel_4()
        {
            this.dbergharel4_5 = new HashSet<dbergharel4_5>();
            this.dbergharelinsert_6 = new HashSet<dbergharelinsert_6>();
        }
    
        public long ID { get; set; }
        public string namegozaresh { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> start { get; set; }
        public string unic { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public string macAdress { get; set; }
        public Nullable<int> FK_usrsabt { get; set; }
        public Nullable<long> FK_table { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<long> FK_namegozarwsh { get; set; }
        public Nullable<int> radifstart { get; set; }
    
        public virtual dberganametanble2_2 dberganametanble2_2 { get; set; }
        public virtual dbergharel_4_4 dbergharel_4_4 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharel4_5> dbergharel4_5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelinsert_6> dbergharelinsert_6 { get; set; }
    }
}
