//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharel2_3
    {
        public long ID { get; set; }
        public Nullable<long> FK_dbergha2 { get; set; }
        public string name { get; set; }
        public Nullable<double> olavait { get; set; }
        public Nullable<int> FK_usrsabt { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public string macAdress { get; set; }
        public Nullable<bool> del { get; set; }
    
        public virtual dbergha2 dbergha2 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
