//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharelrelationseefild_10
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbergharelrelationseefild_10()
        {
            this.dbergharelicratgrouprel11 = new HashSet<dbergharelicratgrouprel11>();
        }
    
        public long ID { get; set; }
        public Nullable<long> fild6 { get; set; }
        public Nullable<long> fild1 { get; set; }
        public Nullable<long> file2 { get; set; }
        public Nullable<long> fild3 { get; set; }
        public Nullable<long> fild4 { get; set; }
        public Nullable<long> fild5 { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<int> koli { get; set; }
        public Nullable<long> fk_2 { get; set; }
        public Nullable<long> FK_input { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelicratgrouprel11> dbergharelicratgrouprel11 { get; set; }
    }
}
