//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharelicratgrouprel8_9
    {
        public long ID { get; set; }
        public Nullable<long> FK_dbergharelicratgroup_8 { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<bool> Kartabl { get; set; }
        public Nullable<bool> raes { get; set; }
        public Nullable<bool> ranndeh { get; set; }
        public Nullable<bool> janshin { get; set; }
        public Nullable<long> del { get; set; }
        public Nullable<int> sayer { get; set; }
    
        public virtual dbergharelicratgroup_8 dbergharelicratgroup_8 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
