//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergapishghan
    {
        public long ID { get; set; }
        public Nullable<long> name { get; set; }
        public Nullable<long> FK_link { get; set; }
        public string string_name { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public Nullable<long> FK_pisghan { get; set; }
        public Nullable<long> namepishghan { get; set; }
        public Nullable<long> FK_gozaresh { get; set; }
    
        public virtual dbergha2 dbergha2 { get; set; }
        public virtual dbergharel4_5 dbergharel4_5 { get; set; }
    }
}
