//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharelimsertfk1_7_GIS
    {
        public long ID { get; set; }
        public Nullable<long> FK_dbergharelinsert_6 { get; set; }
        public string valuunic { get; set; }
        public Nullable<long> FK_db2 { get; set; }
        public string valueFK_db2 { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public Nullable<int> FK_usrsabt { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
    
        public virtual dbergha2 dbergha2 { get; set; }
        public virtual dbergharelinsert_6 dbergharelinsert_6 { get; set; }
    }
}
