//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharelicratgroup_8
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbergharelicratgroup_8()
        {
            this.dbergharelicratgrouprel8_9 = new HashSet<dbergharelicratgrouprel8_9>();
        }
    
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<long> FK_mashin { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<int> usrsabt { get; set; }
        public string fullnamesabt { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public Nullable<int> personalID { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelicratgrouprel8_9> dbergharelicratgrouprel8_9 { get; set; }
    }
}
