//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbergharelicreatejob13
    {
        public long ID { get; set; }
        public string unic { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> pardakhtShod { get; set; }
        public Nullable<long> taghsitBedehi { get; set; }
        public Nullable<System.DateTime> miladi_date1 { get; set; }
        public Nullable<int> darbBasteh { get; set; }
        public Nullable<int> mamanetAzAnjamKar { get; set; }
        public Nullable<int> ensheabGhatMovaghat { get; set; }
        public Nullable<int> ensheabJamAvaryShodeh { get; set; }
        public Nullable<int> moghayratFazBaAmper { get; set; }
        public Nullable<int> dastkariDarKontor { get; set; }
        public Nullable<int> kontorKharabAst { get; set; }
        public Nullable<int> barghGheyrMojazAzShabakeh { get; set; }
        public Nullable<int> azGhalamOftadeh { get; set; }
        public Nullable<int> eslahShomareHamrah { get; set; }
        public string fullnamesabt { get; set; }
        public Nullable<int> fK_sbt { get; set; }
        public Nullable<int> personaID { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public Nullable<long> FK_db2 { get; set; }
        public Nullable<long> FK_tb12 { get; set; }
    
        public virtual dbergharelicratgrouprel11 dbergharelicratgrouprel11 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
