//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbGIS_USR_after
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<double> mogtasat_x { get; set; }
        public Nullable<double> mogtasat_y { get; set; }
        public string mogtasat_x_nva { get; set; }
        public string mogtasat_y_nva { get; set; }
        public string unic { get; set; }
        public string cod_car { get; set; }
        public Nullable<long> FK_erja { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
