//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbGIS_USR
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public string x_nvar { get; set; }
        public string y_nvar { get; set; }
        public Nullable<int> city { get; set; }
        public string city_name { get; set; }
    
        public virtual tbCities tbCities { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
