//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbLInkmagmo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbLInkmagmo()
        {
            this.dbLInkmagmo1 = new HashSet<dbLInkmagmo>();
        }
    
        public int ID { get; set; }
        public string nameaval { get; set; }
        public Nullable<int> reltaiontable { get; set; }
        public Nullable<int> NUMber { get; set; }
        public Nullable<int> radif { get; set; }
        public string NUMberstring { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbLInkmagmo> dbLInkmagmo1 { get; set; }
        public virtual dbLInkmagmo dbLInkmagmo2 { get; set; }
    }
}
