//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dblog
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public string Action { get; set; }
        public string sharh { get; set; }
        public string MACADDRESS { get; set; }
        public string KODOMSafhe { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string FULLname { get; set; }
        public Nullable<int> personalID { get; set; }
        public string View_site { get; set; }
        public string PersianDate { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
