//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsathdastressi3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbsathdastressi3()
        {
            this.dbsathdastressi4 = new HashSet<dbsathdastressi4>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_dbsathdastressi2 { get; set; }
        public string name { get; set; }
    
        public virtual dbsathdastressi2 dbsathdastressi2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbsathdastressi4> dbsathdastressi4 { get; set; }
    }
}
