//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbsathdastressi4
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<long> FK_dbsathdastressi3 { get; set; }
        public Nullable<bool> vaziatt { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> datatim { get; set; }
        public Nullable<long> FK_dbsathdastressi2 { get; set; }
        public Nullable<long> FK_dbsathdastressi1 { get; set; }
    
        public virtual dbsathdastressi1 dbsathdastressi1 { get; set; }
        public virtual dbsathdastressi2 dbsathdastressi2 { get; set; }
        public virtual dbsathdastressi3 dbsathdastressi3 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
