//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtarifmahdodayt5
    {
        public int ID { get; set; }
        public Nullable<int> FK_marhal4 { get; set; }
        public Nullable<int> FK_Pymn { get; set; }
        public Nullable<int> FK_moalf { get; set; }
        public Nullable<int> FK_city { get; set; }
        public Nullable<long> value { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCities tbCities { get; set; }
        public virtual dbtarifmahdodayt1 dbtarifmahdodayt1 { get; set; }
        public virtual dbtarifmahdodayt3 dbtarifmahdodayt3 { get; set; }
    }
}
