//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtarifmahdodayt4
    {
        public int ID { get; set; }
        public Nullable<int> FK_name { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<bool> Position { get; set; }
    
        public virtual dbtarifmahdodayt3 dbtarifmahdodayt3 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
