//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbtarifmovazaf
    {
        public int ID { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> parttime { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<System.TimeSpan> start_clock { get; set; }
        public Nullable<System.TimeSpan> end_clock { get; set; }
        public string start_clock2 { get; set; }
        public string end_clock2 { get; set; }
        public Nullable<int> FK_tariff { get; set; }
    
        public virtual dbtarifvazifehasli dbtarifvazifehasli { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
