//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbvaziathozor
    {
        public int ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<System.DateTime> datattime { get; set; }
        public Nullable<System.TimeSpan> start_clock { get; set; }
        public Nullable<System.TimeSpan> end_clock { get; set; }
        public Nullable<int> level_time { get; set; }
        public Nullable<int> type_notwork { get; set; }
        public Nullable<System.TimeSpan> start_clock2 { get; set; }
        public Nullable<System.TimeSpan> end_clock2 { get; set; }
        public Nullable<int> level_time2 { get; set; }
        public Nullable<int> type_notwork2 { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
