//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbvaziat_FIsh1Set
    {
        public long ID { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> yaer { get; set; }
        public Nullable<int> vaz { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> saf { get; set; }
    }
}
