//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descriptionsorat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Descriptionsorat()
        {
            this.TbDescriptionDetail = new HashSet<TbDescriptionDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_Pymn { get; set; }
        public Nullable<int> FK_Radif { get; set; }
        public Nullable<long> value { get; set; }
        public string Description { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCreditIndicators tbCreditIndicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbDescriptionDetail> TbDescriptionDetail { get; set; }
    }
}
