//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class erja_omomi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public erja_omomi()
        {
            this.erja_like_link = new HashSet<erja_like_link>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_gozaresh { get; set; }
        public Nullable<long> FK_link { get; set; }
        public Nullable<bool> unic { get; set; }
        public Nullable<int> vaziat { get; set; }
        public string title { get; set; }
        public Nullable<long> FK_job { get; set; }
        public Nullable<long> FK_link_cjeek { get; set; }
        public Nullable<long> FK_gozaresh_cheeck { get; set; }
        public Nullable<int> dargeshavad { get; set; }
    
        public virtual dberganametanble2_2 dberganametanble2_2 { get; set; }
        public virtual dbergha2 dbergha2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erja_like_link> erja_like_link { get; set; }
    }
}
