//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class erja_sabt_usr
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<long> FK_omomi { get; set; }
        public Nullable<long> unic { get; set; }
        public Nullable<System.DateTime> timesabt_vaz0 { get; set; }
        public Nullable<System.DateTime> timesabt_vaz1 { get; set; }
        public Nullable<System.DateTime> timesabt_vaz2 { get; set; }
        public Nullable<long> FK_erja_omomi_edit { get; set; }
        public string value_str { get; set; }
        public Nullable<long> value_int { get; set; }
        public Nullable<System.DateTime> value_time { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<bool> value_cheek { get; set; }
    
        public virtual erja_like erja_like { get; set; }
        public virtual erja_omomi_edit erja_omomi_edit { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
