//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class erja_like
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public erja_like()
        {
            this.erja_like_link = new HashSet<erja_like_link>();
            this.erja_sabt_usr = new HashSet<erja_sabt_usr>();
        }
    
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public string unic { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<long> del { get; set; }
        public Nullable<long> FK_job { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erja_like_link> erja_like_link { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erja_sabt_usr> erja_sabt_usr { get; set; }
    }
}
