//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class erja_omomi_edit_link
    {
        public long ID { get; set; }
        public Nullable<long> FK_erja_omomi_edit { get; set; }
        public string value { get; set; }
        public Nullable<long> vaziat { get; set; }
        public Nullable<int> numeber { get; set; }
    
        public virtual erja_omomi_edit erja_omomi_edit { get; set; }
    }
}
