//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class erja_omomi_edit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public erja_omomi_edit()
        {
            this.erja_omomi_edit_link = new HashSet<erja_omomi_edit_link>();
            this.erja_sabt_usr = new HashSet<erja_sabt_usr>();
        }
    
        public long ID { get; set; }
        public string Nam { get; set; }
        public Nullable<int> Model { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> Fk_Shooghl { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<int> asli { get; set; }
        public Nullable<long> shomareh { get; set; }
        public Nullable<long> FK_gozarsh { get; set; }
        public Nullable<long> numberr { get; set; }
        public string valustri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erja_omomi_edit_link> erja_omomi_edit_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erja_sabt_usr> erja_sabt_usr { get; set; }
    }
}
