//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstedadNiroEnsani
    {
        public long ID { get; set; }
        public Nullable<int> Fk_User { get; set; }
        public string SaatShoro { get; set; }
        public string SaatKhateme { get; set; }
        public Nullable<System.DateTime> SaatShoro1 { get; set; }
        public Nullable<System.DateTime> SaatKhateme1 { get; set; }
        public string SaatVorod { get; set; }
        public string SaatKhorog { get; set; }
        public Nullable<System.DateTime> SaatVorod1 { get; set; }
        public Nullable<System.DateTime> SaatKhorog1 { get; set; }
        public Nullable<int> Vaziat { get; set; }
        public Nullable<System.DateTime> Timesabt { get; set; }
        public Nullable<long> UserSabt { get; set; }
        public string FullNameSabt { get; set; }
        public Nullable<int> PersonalIdSabt { get; set; }
        public string Sharh { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
