//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialDocuments
    {
        public int ID { get; set; }
        public Nullable<int> Peyman_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Creditlamdicatros_ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DataDocument { get; set; }
        public Nullable<double> Debtore { get; set; }
        public Nullable<double> Creditor { get; set; }
        public string File_SystemName { get; set; }
        public string File_RealName { get; set; }
        public Nullable<int> Detailedtitle_ID { get; set; }
        public string Rigstertime { get; set; }
        public string MacAdress { get; set; }
        public Nullable<int> FK_final { get; set; }
        public Nullable<long> numberpayvas { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        public virtual tbCreditIndicators tbCreditIndicators { get; set; }
        public virtual tbDetailedtitle tbDetailedtitle { get; set; }
        public virtual tbfkfinancial tbfkfinancial { get; set; }
    }
}
