//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class gozaresh_1121_Fish
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<long> count { get; set; }
        public Nullable<int> type_deman { get; set; }
        public Nullable<int> type_shari { get; set; }
        public Nullable<int> type_takfaz { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<double> moadel { get; set; }
        public Nullable<long> moadel_big { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public Nullable<System.DateTime> time_sabt { get; set; }
        public Nullable<int> usrsabt { get; set; }
        public string FULL_name_sabt { get; set; }
        public Nullable<int> cod_person { get; set; }
        public string type_deman1 { get; set; }
        public string type_shari1 { get; set; }
        public string type_takfaz1 { get; set; }
        public Nullable<long> FK_gozaresh { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
