//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosh1
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public string soal { get; set; }
        public string pasogh { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> iscorect { get; set; }
        public string sharh { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
