//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KasriMashin
    {
        public int ID { get; set; }
        public Nullable<int> Fk_pymn { get; set; }
        public Nullable<int> Fk_bunch { get; set; }
        public Nullable<int> number_sorat { get; set; }
        public Nullable<double> Value { get; set; }
    
        public virtual tbEquipmentBunch tbEquipmentBunch { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
