//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link_User_And_Moalefe
    {
        public int Link_User_And_Moalefe_ID { get; set; }
        public Nullable<int> FK_Moalefe_ID { get; set; }
        public Nullable<int> FK_User_ID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Moalefe_Value { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
