//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDastrasi
    {
        public long ID { get; set; }
        public string Sharh { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> AsTime { get; set; }
        public Nullable<System.DateTime> TaTime { get; set; }
        public Nullable<System.DateTime> TimeSabt { get; set; }
        public Nullable<int> UserSabt { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
