//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class madarek_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public madarek_1()
        {
            this.madarek_linkcheack_2 = new HashSet<madarek_linkcheack_2>();
            this.madarek_linkesabt_3 = new HashSet<madarek_linkesabt_3>();
            this.madarek_sabtdoreh_4 = new HashSet<madarek_sabtdoreh_4>();
        }
    
        public long ID { get; set; }
        public string name { get; set; }
        public string sharh { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> usrsabt { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_linkcheack_2> madarek_linkcheack_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_linkesabt_3> madarek_linkesabt_3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_sabtdoreh_4> madarek_sabtdoreh_4 { get; set; }
    }
}
