//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class madarek_vaziatdoreh_8
    {
        public long ID { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<int> del { get; set; }
    }
}
