//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class madarek_linkcheack_2
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> usrdabt { get; set; }
        public string fullnamesabt { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public Nullable<long> FK_namemadark { get; set; }
    
        public virtual madarek_1 madarek_1 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
