//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class madarek_vaziatdoreh_6
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public madarek_vaziatdoreh_6()
        {
            this.madarek_vaziatdoreh_7 = new HashSet<madarek_vaziatdoreh_7>();
        }
    
        public long ID { get; set; }
        public Nullable<int> type { get; set; }
        public string name { get; set; }
        public Nullable<int> del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_vaziatdoreh_7> madarek_vaziatdoreh_7 { get; set; }
    }
}
