//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class madarek_sabtdoreh_4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public madarek_sabtdoreh_4()
        {
            this.madarek_vaziatdoreh_5 = new HashSet<madarek_vaziatdoreh_5>();
        }
    
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public string System_FIle { get; set; }
        public string Realname_namefile { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public Nullable<long> FK_namedoreh { get; set; }
        public string sharh { get; set; }
        public Nullable<int> vaziat { get; set; }
    
        public virtual madarek_1 madarek_1 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_vaziatdoreh_5> madarek_vaziatdoreh_5 { get; set; }
    }
}
