//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NatigeEshterakBala50
    {
        public long ID { get; set; }
        public string NameMoshtarak { get; set; }
        public string ShenaseGhabz { get; set; }
        public string MandeKolErja { get; set; }
        public string MandeKolBeroz1 { get; set; }
        public Nullable<long> MandeKolBeroz2 { get; set; }
        public Nullable<int> NatigePeygiri { get; set; }
        public string SharhPeygiri { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<System.DateTime> time_sabt { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> UserSabt { get; set; }
        public string city_name { get; set; }
        public string value_bi { get; set; }
        public string tarigh_frosh { get; set; }
        public string tarigh_vosol { get; set; }
        public string time_shamsi { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
