//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class olaviat_1218_alsil_olvaiat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public olaviat_1218_alsil_olvaiat()
        {
            this.olaviat_1218_link_olaviat = new HashSet<olaviat_1218_link_olaviat>();
        }
    
        public long ID { get; set; }
        public string name { get; set; }
        public Nullable<long> olavait { get; set; }
        public Nullable<long> vaziat { get; set; }
        public string name_2 { get; set; }
        public string time { get; set; }
        public Nullable<long> olaviat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olaviat_1218_link_olaviat> olaviat_1218_link_olaviat { get; set; }
    }
}
