//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class olaviat_1218_link_olaviat
    {
        public long ID { get; set; }
        public Nullable<long> FK_link { get; set; }
        public Nullable<long> FK_gozaresh1 { get; set; }
        public Nullable<long> FK_gozaresh2 { get; set; }
        public Nullable<long> FK_name { get; set; }
        public Nullable<long> FK_name2 { get; set; }
        public string val1 { get; set; }
        public string val2 { get; set; }
        public string val3 { get; set; }
        public string shart { get; set; }
        public Nullable<long> shart_tik { get; set; }
        public Nullable<long> olaviat { get; set; }
        public string unic { get; set; }
        public Nullable<long> unic_tik { get; set; }
        public Nullable<long> actove { get; set; }
        public Nullable<long> alamat { get; set; }
        public string alamat_tik { get; set; }
        public Nullable<System.DateTime> time_sabt { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public string time_sabt_n { get; set; }
        public string FK_gozaresh2_name { get; set; }
        public string FK_gozaresh_name { get; set; }
        public string FK_name_name { get; set; }
        public string FK_name2_name { get; set; }
        public Nullable<long> val1_big { get; set; }
        public Nullable<long> val2_big { get; set; }
        public Nullable<long> val3_big { get; set; }
        public string titel { get; set; }
        public string titel2 { get; set; }
        public string titel3 { get; set; }
        public Nullable<int> vaziat_moh { get; set; }
    
        public virtual dbergha2 dbergha2 { get; set; }
        public virtual dbergha2 dbergha21 { get; set; }
        public virtual dbergharel_4_4 dbergharel_4_4 { get; set; }
        public virtual dbergharel_4_4 dbergharel_4_41 { get; set; }
        public virtual olaviat_1218_alsil_olvaiat olaviat_1218_alsil_olvaiat { get; set; }
    }
}
