//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class olaviat_1218
    {
        public long ID { get; set; }
        public string name { get; set; }
        public Nullable<long> olaviat { get; set; }
        public Nullable<long> active { get; set; }
        public Nullable<long> vaziat { get; set; }
        public string terst_st { get; set; }
    }
}
