//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class olaviat_1218_link
    {
        public long ID { get; set; }
        public Nullable<long> FK_olaviat { get; set; }
        public string input1 { get; set; }
        public Nullable<long> input2 { get; set; }
        public Nullable<long> FK_db2 { get; set; }
        public Nullable<long> FK_db4_4 { get; set; }
        public Nullable<long> mablagh1_1 { get; set; }
        public Nullable<long> vaziat1 { get; set; }
        public Nullable<long> mablagh1_2 { get; set; }
        public Nullable<long> vaziat2 { get; set; }
        public Nullable<long> vaziatasli { get; set; }
        public string name { get; set; }
        public string name2 { get; set; }
        public string time { get; set; }
        public Nullable<long> olavat { get; set; }
    
        public virtual dbergha2 dbergha2 { get; set; }
        public virtual dbergharel_4_4 dbergharel_4_4 { get; set; }
        public virtual olaviat_1218_alsil olaviat_1218_alsil { get; set; }
    }
}
