//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class otamasoin2_crettype
    {
        public long ID { get; set; }
        public Nullable<long> FK_otamasoin1_createshagheh { get; set; }
        public string name { get; set; }
        public Nullable<int> vaziatx { get; set; }
        public Nullable<int> vazity { get; set; }
        public Nullable<int> vaiat { get; set; }
        public Nullable<int> usrsabt { get; set; }
        public Nullable<int> vaziatcolx { get; set; }
        public Nullable<int> vazitcly { get; set; }
        public string stylr { get; set; }
    
        public virtual otamasoin1_createshagheh otamasoin1_createshagheh { get; set; }
    }
}
