//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class otamasoin1_createshagheh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public otamasoin1_createshagheh()
        {
            this.otamasoin2_crettype = new HashSet<otamasoin2_crettype>();
        }
    
        public long ID { get; set; }
        public string name { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<int> sabtusr { get; set; }
        public Nullable<int> vazit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<otamasoin2_crettype> otamasoin2_crettype { get; set; }
    }
}
