//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Result1218_Rejected2
    {
        public long ID { get; set; }
        public string valuunic { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Input_Day_ASL { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public string TotalVosol { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    }
}
