//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Result1218_tarigh
    {
        public long ID { get; set; }
        public string start_tme { get; set; }
        public string strart_end { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<int> active { get; set; }
    }
}
