//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Khodro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Khodro()
        {
            this.estedad_khodro = new HashSet<estedad_khodro>();
            this.tbSabtEstedadKhodro = new HashSet<tbSabtEstedadKhodro>();
        }
    
        public long ID { get; set; }
        public string PelakKharej { get; set; }
        public string PelakDakhel { get; set; }
        public Nullable<long> Model { get; set; }
        public Nullable<long> Rang { get; set; }
        public Nullable<long> Noe { get; set; }
        public Nullable<bool> Uniform { get; set; }
        public Nullable<int> SaleSakht { get; set; }
        public Nullable<long> KarkardKilometr { get; set; }
        public Nullable<int> Fk_UserMalekHamkarEdare { get; set; }
        public string NamKharejMalek { get; set; }
        public string CodeMeliKharejMalek { get; set; }
        public Nullable<System.DateTime> TavalodKharejMalek { get; set; }
        public Nullable<int> Fk_UserRanandeHamkarEdare1 { get; set; }
        public Nullable<int> Fk_UserRanandeHamkarEdare2 { get; set; }
        public Nullable<int> Fk_UserRanandeHamkarEdare3 { get; set; }
        public string NamKharejRanande1 { get; set; }
        public string NamKharejRanande2 { get; set; }
        public string NamKharejRanande3 { get; set; }
        public string CodeMeliKharejRanande1 { get; set; }
        public string CodeMeliKharejRanande2 { get; set; }
        public string CodeMeliKharejRanande3 { get; set; }
        public Nullable<System.DateTime> TavalodKharejRanande1 { get; set; }
        public Nullable<System.DateTime> TavalodKharejRanande2 { get; set; }
        public Nullable<System.DateTime> TavalodKharejRanande3 { get; set; }
        public string ShomareTamasKharejRanande1 { get; set; }
        public string ShomareTamasKharejRanande2 { get; set; }
        public string ShomareTamasKharejRanande3 { get; set; }
        public string CodePostKharejRanande1 { get; set; }
        public string CodePostKharejRanande2 { get; set; }
        public string CodePostKharejRanande3 { get; set; }
        public string AdresKharejRanande1 { get; set; }
        public string AdresKharejRanande2 { get; set; }
        public string AdresKharejRanande3 { get; set; }
        public Nullable<int> VaziatSalamatKhodro { get; set; }
        public Nullable<long> DalayelPishfarz { get; set; }
        public string Sharh { get; set; }
        public Nullable<System.DateTime> TarikhKhatemeEtebar { get; set; }
        public string SherkatBimegar { get; set; }
        public Nullable<int> VaziatBimeShakhsSales { get; set; }
        public Nullable<int> VaziatMoayeneFani { get; set; }
        public Nullable<int> vaziat_hazf { get; set; }
    
        public virtual createmashin createmashin { get; set; }
        public virtual createmoshkelmashin createmoshkelmashin { get; set; }
        public virtual createrang createrang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estedad_khodro> estedad_khodro { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        public virtual tbUsers tbUsers1 { get; set; }
        public virtual tbUsers tbUsers2 { get; set; }
        public virtual tbUsers tbUsers3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSabtEstedadKhodro> tbSabtEstedadKhodro { get; set; }
    }
}
