//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_1118_Fish
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<long> shari_demand { get; set; }
        public Nullable<long> shahri_takfaz { get; set; }
        public Nullable<long> shari_sefaz { get; set; }
        public Nullable<long> rostaee_demand { get; set; }
        public Nullable<long> rostaeei_takfaz { get; set; }
        public Nullable<long> rostaei_sefaz { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<long> gpzaresh { get; set; }
        public Nullable<long> chareg_eamand { get; set; }
        public Nullable<long> charegh_takfaz { get; set; }
        public Nullable<long> charesg_sefaz { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
