//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Admin
    {
        public int ID { get; set; }
        public string userName { get; set; }
        public string Pass_1 { get; set; }
        public string Pass_2 { get; set; }
        public int ActiveCode { get; set; }
        public bool isActive { get; set; }
        public string Picture { get; set; }
        public System.DateTime RegisterDate { get; set; }
    }
}
