//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SellerSetting
    {
        public int Count_Peyman { get; set; }
        public int Count_RealUsers { get; set; }
        public int Count_LegalUsers { get; set; }
        public System.DateTime SoftwareExpirationDate { get; set; }
        public string SoftwareWorkGeography { get; set; }
        public string SoftwareWorkGIS_X { get; set; }
        public string SoftwareWorkGIS_Y { get; set; }
        public int MaxUserInactivityTime { get; set; }
        public string MacAddress { get; set; }
        public int id { get; set; }
    }
}
