//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Step_tax
    {
        public int ID { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<double> Fromamount { get; set; }
        public Nullable<double> Toamount { get; set; }
        public Nullable<double> Percent_amount { get; set; }
        public Nullable<int> year { get; set; }
    }
}
