//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Subset_of_installments
    {
        public int Subsetins_ID { get; set; }
        public int fk_installment_ID { get; set; }
        public int value { get; set; }
        public int number { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
    
        public virtual tbinstallments tbinstallments { get; set; }
    }
}
