//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAdamShahr
    {
        public int ID { get; set; }
        public Nullable<int> idshahr { get; set; }
        public Nullable<int> idkarbar { get; set; }
        public Nullable<int> value { get; set; }
    
        public virtual tbCities tbCities { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
