//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAddReduceMoadelkarkard
    {
        public int addred_ID { get; set; }
        public Nullable<int> FKUser { get; set; }
        public Nullable<int> addred_Month { get; set; }
        public Nullable<int> addred_Year { get; set; }
        public Nullable<double> addred_Value { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
