//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBannerSlider
    {
        public int ID { get; set; }
        public string ImgDir { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string TextTop { get; set; }
        public string TextCenter { get; set; }
        public string TextDown { get; set; }
        public string ColorTop { get; set; }
        public string ColorCenter { get; set; }
        public string ColorDown { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
