//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBackup1
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.TimeSpan> clock { get; set; }
        public Nullable<int> DOreh { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
