//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBusinessSide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBusinessSide()
        {
            this.tbBusinessSide1 = new HashSet<tbBusinessSide>();
            this.tbLink_UserAndAction = new HashSet<tbLink_UserAndAction>();
            this.tbUser_link_BusinessSide = new HashSet<tbUser_link_BusinessSide>();
        }
    
        public int up_Id { get; set; }
        public string up_name { get; set; }
        public Nullable<int> FK_Parent_ID { get; set; }
        public string up_Duties { get; set; }
        public string up_workTime { get; set; }
        public string up_experience { get; set; }
        public string up_Safety_Skills { get; set; }
        public string up_Special_Skills { get; set; }
        public string up_General_Skills { get; set; }
        public Nullable<int> up_em_Gender { get; set; }
        public Nullable<int> up_minimum_Edu { get; set; }
        public string up_General_Equipment { get; set; }
        public string up_Specialized_Equipment { get; set; }
        public string up_work_Space { get; set; }
        public string up_Related_Jobs { get; set; }
        public string up_Authority { get; set; }
        public Nullable<bool> up_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBusinessSide> tbBusinessSide1 { get; set; }
        public virtual tbBusinessSide tbBusinessSide2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLink_UserAndAction> tbLink_UserAndAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser_link_BusinessSide> tbUser_link_BusinessSide { get; set; }
    }
}
