//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCaranSettings
    {
        public int CaranS_ID { get; set; }
        public Nullable<int> FK_Moalefe_ID { get; set; }
        public Nullable<double> CaranMin { get; set; }
        public Nullable<double> CaranMax { get; set; }
        public Nullable<double> CaranAcceptLimit { get; set; }
        public Nullable<double> CaranCriterion { get; set; }
        public Nullable<double> CaranStandard { get; set; }
        public Nullable<double> CaranAyabOZahab { get; set; }
        public Nullable<double> CaranAstaneShoroPadash { get; set; }
        public Nullable<double> CaranSaranePadash { get; set; }
        public Nullable<double> CaranAstaneShoroJarime { get; set; }
        public Nullable<double> CaranSaraneJarime { get; set; }
        public Nullable<double> caranmablagh { get; set; }
        public Nullable<bool> sarmayeh { get; set; }
        public Nullable<bool> zarib_sharestan { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
    }
}
