//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcheackfishforusers
    {
        public int ID { get; set; }
        public Nullable<int> FK_User { get; set; }
        public Nullable<bool> HasFish { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
    }
}
