//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCities()
        {
            this.tbCaranSettings_zarib = new HashSet<tbCaranSettings_zarib>();
            this.tbEquipmentMoalefeValueReffrenceSave = new HashSet<tbEquipmentMoalefeValueReffrenceSave>();
            this.tblink_moalfe_city = new HashSet<tblink_moalfe_city>();
            this.tbmarahlsabtbastedit2 = new HashSet<tbmarahlsabtbastedit2>();
            this.tbsabtbasteh1 = new HashSet<tbsabtbasteh1>();
            this.tbvaziat_mahdodayt = new HashSet<tbvaziat_mahdodayt>();
            this.Create_linkjob_2 = new HashSet<Create_linkjob_2>();
            this.dbGIS_USR = new HashSet<dbGIS_USR>();
            this.dbzaribshogl = new HashSet<dbzaribshogl>();
            this.tbAdamShahr = new HashSet<tbAdamShahr>();
            this.dbtarifmahdodayt5 = new HashSet<dbtarifmahdodayt5>();
            this.tbmoalfefishexcel = new HashSet<tbmoalfefishexcel>();
            this.tbpeymancities = new HashSet<tbpeymancities>();
            this.tbSavedFunctions = new HashSet<tbSavedFunctions>();
            this.tbsaveSoratBasteh = new HashSet<tbsaveSoratBasteh>();
            this.tbSoratSavefromExcelMoalfe = new HashSet<tbSoratSavefromExcelMoalfe>();
            this.tbSoratvaziat = new HashSet<tbSoratvaziat>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> ZaribSharestan { get; set; }
        public Nullable<double> Zaribmalyat { get; set; }
        public Nullable<double> Max_ezafeh { get; set; }
        public Nullable<double> Ayab_zohab { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCaranSettings_zarib> tbCaranSettings_zarib { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValueReffrenceSave> tbEquipmentMoalefeValueReffrenceSave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblink_moalfe_city> tblink_moalfe_city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahlsabtbastedit2> tbmarahlsabtbastedit2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsabtbasteh1> tbsabtbasteh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbvaziat_mahdodayt> tbvaziat_mahdodayt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Create_linkjob_2> Create_linkjob_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbGIS_USR> dbGIS_USR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbzaribshogl> dbzaribshogl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAdamShahr> tbAdamShahr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtarifmahdodayt5> dbtarifmahdodayt5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoalfefishexcel> tbmoalfefishexcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbpeymancities> tbpeymancities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSavedFunctions> tbSavedFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsaveSoratBasteh> tbsaveSoratBasteh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSoratSavefromExcelMoalfe> tbSoratSavefromExcelMoalfe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSoratvaziat> tbSoratvaziat { get; set; }
    }
}
