//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContractMoalefeDastmozdi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbContractMoalefeDastmozdi()
        {
            this.Link_User_And_Moalefe = new HashSet<Link_User_And_Moalefe>();
            this.tbCaranSettings = new HashSet<tbCaranSettings>();
            this.tbCaranSettings_zarib = new HashSet<tbCaranSettings_zarib>();
            this.tbControllyPanel = new HashSet<tbControllyPanel>();
            this.dbolavaitkasri1 = new HashSet<dbolavaitkasri1>();
            this.dbtarifmahdodayt1 = new HashSet<dbtarifmahdodayt1>();
            this.dbtarifmahdodayt6 = new HashSet<dbtarifmahdodayt6>();
            this.tblink_moalfe_city = new HashSet<tblink_moalfe_city>();
            this.SettingVisableShowMoalefe = new HashSet<SettingVisableShowMoalefe>();
            this.tbControllyPeyman = new HashSet<tbControllyPeyman>();
            this.tbDocumentsDefinitionOfDocumentTitles = new HashSet<tbDocumentsDefinitionOfDocumentTitles>();
            this.tbExcelDocument = new HashSet<tbExcelDocument>();
            this.tbFormula = new HashSet<tbFormula>();
            this.tbHighLowMoalefeVal = new HashSet<tbHighLowMoalefeVal>();
            this.tbinstallments = new HashSet<tbinstallments>();
            this.tbkarkard_notsystem = new HashSet<tbkarkard_notsystem>();
            this.tbLogFunctions = new HashSet<tbLogFunctions>();
            this.tbmadel_kar1 = new HashSet<tbmadel_kar1>();
            this.tbmarahelsabt2 = new HashSet<tbmarahelsabt2>();
            this.tbmarahlsabtbastedit3 = new HashSet<tbmarahlsabtbastedit3>();
            this.tbmarahlsabtbastedit6 = new HashSet<tbmarahlsabtbastedit6>();
            this.tbmarahlsabtbastedit61 = new HashSet<tbmarahlsabtbastedit6>();
            this.tbmarahlsabtbastedit7 = new HashSet<tbmarahlsabtbastedit7>();
            this.tbmoadel_kar2 = new HashSet<tbmoadel_kar2>();
            this.tbMoalefeDastmozdiValueFromExcel = new HashSet<tbMoalefeDastmozdiValueFromExcel>();
            this.tbMoalefeValeFishTest = new HashSet<tbMoalefeValeFishTest>();
            this.tbMoalefeValue = new HashSet<tbMoalefeValue>();
            this.tbMoalefeValueFish = new HashSet<tbMoalefeValueFish>();
            this.tbMoalefeValuePishkhan = new HashSet<tbMoalefeValuePishkhan>();
            this.tbMoalefeValueSorat = new HashSet<tbMoalefeValueSorat>();
            this.tbmoalfehkasri = new HashSet<tbmoalfehkasri>();
            this.tbolaviat_frml = new HashSet<tbolaviat_frml>();
            this.tbReffrenceSaveLevelMoalefe = new HashSet<tbReffrenceSaveLevelMoalefe>();
            this.tbSoratSavefromExcelMoalfe = new HashSet<tbSoratSavefromExcelMoalfe>();
            this.tbUserContractsAndMoalefeGhararDadi = new HashSet<tbUserContractsAndMoalefeGhararDadi>();
            this.tbUserContractsAndMoalefeGhararDadi1 = new HashSet<tbUserContractsAndMoalefeGhararDadi1>();
            this.tbvalue_frml = new HashSet<tbvalue_frml>();
            this.vaziatsoratvaziat = new HashSet<vaziatsoratvaziat>();
        }
    
        public int md_ID { get; set; }
        public string md_variable { get; set; }
        public Nullable<int> md_Type { get; set; }
        public string md_Title { get; set; }
        public Nullable<bool> md_IsActive { get; set; }
        public Nullable<int> FK_Category_ID { get; set; }
        public Nullable<int> FK_UnitParameter { get; set; }
        public Nullable<int> included { get; set; }
        public Nullable<int> Deduction_or_addition { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<bool> ISdays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link_User_And_Moalefe> Link_User_And_Moalefe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCaranSettings> tbCaranSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCaranSettings_zarib> tbCaranSettings_zarib { get; set; }
        public virtual tbCategories tbCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbControllyPanel> tbControllyPanel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbolavaitkasri1> dbolavaitkasri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtarifmahdodayt1> dbtarifmahdodayt1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtarifmahdodayt6> dbtarifmahdodayt6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblink_moalfe_city> tblink_moalfe_city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SettingVisableShowMoalefe> SettingVisableShowMoalefe { get; set; }
        public virtual tbUnitParameter tbUnitParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbControllyPeyman> tbControllyPeyman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocumentsDefinitionOfDocumentTitles> tbDocumentsDefinitionOfDocumentTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbExcelDocument> tbExcelDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFormula> tbFormula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHighLowMoalefeVal> tbHighLowMoalefeVal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbinstallments> tbinstallments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbkarkard_notsystem> tbkarkard_notsystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLogFunctions> tbLogFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmadel_kar1> tbmadel_kar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahelsabt2> tbmarahelsabt2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahlsabtbastedit3> tbmarahlsabtbastedit3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahlsabtbastedit6> tbmarahlsabtbastedit6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahlsabtbastedit6> tbmarahlsabtbastedit61 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahlsabtbastedit7> tbmarahlsabtbastedit7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoadel_kar2> tbmoadel_kar2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeDastmozdiValueFromExcel> tbMoalefeDastmozdiValueFromExcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValeFishTest> tbMoalefeValeFishTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValue> tbMoalefeValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValueFish> tbMoalefeValueFish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValuePishkhan> tbMoalefeValuePishkhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValueSorat> tbMoalefeValueSorat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoalfehkasri> tbmoalfehkasri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbolaviat_frml> tbolaviat_frml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceSaveLevelMoalefe> tbReffrenceSaveLevelMoalefe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSoratSavefromExcelMoalfe> tbSoratSavefromExcelMoalfe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserContractsAndMoalefeGhararDadi> tbUserContractsAndMoalefeGhararDadi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserContractsAndMoalefeGhararDadi1> tbUserContractsAndMoalefeGhararDadi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbvalue_frml> tbvalue_frml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaziatsoratvaziat> vaziatsoratvaziat { get; set; }
    }
}
