//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContractJobGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbContractJobGroup()
        {
            this.tbContractJobGroupValues = new HashSet<tbContractJobGroupValues>();
        }
    
        public int jg_ID { get; set; }
        public string jg_HagheMaskan { get; set; }
        public string jg_HagheOlad { get; set; }
        public string jg_KharoBar { get; set; }
        public Nullable<System.DateTime> jg_CreateTime { get; set; }
        public Nullable<int> FK_UserCreated { get; set; }
        public Nullable<int> jg_Year { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string title { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbContractJobGroupValues> tbContractJobGroupValues { get; set; }
    }
}
