//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcount_car
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> dday { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<double> count { get; set; }
        public Nullable<double> mantaghe { get; set; }
        public Nullable<long> count_big1 { get; set; }
        public Nullable<System.DateTime> time_sabt { get; set; }
        public Nullable<int> usr_sabt { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<System.DateTime> time_end { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
