//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCommodityProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCommodityProject()
        {
            this.tbProduct_project_Accept = new HashSet<tbProduct_project_Accept>();
        }
    
        public int Id { get; set; }
        public int FK_PeymanContracts { get; set; }
        public int City_Id { get; set; }
        public string ProjectCode { get; set; }
        public System.DateTime DateOfDefinitionCommodityProject { get; set; }
        public string ProjectTitle { get; set; }
        public bool P_Active { get; set; }
        public long Totalnumber { get; set; }
        public string File_SystemName { get; set; }
        public string File_RealName { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProduct_project_Accept> tbProduct_project_Accept { get; set; }
    }
}
