//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompanies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCompanies()
        {
            this.tbPeymanContracts = new HashSet<tbPeymanContracts>();
            this.tbPeymanContracts1 = new HashSet<tbPeymanContracts>();
            this.tbPeymanContracts2 = new HashSet<tbPeymanContracts>();
            this.tbUserContracts = new HashSet<tbUserContracts>();
            this.tbUserContracts1 = new HashSet<tbUserContracts>();
            this.dbAsnadCheack4 = new HashSet<dbAsnadCheack4>();
            this.dbAsnadDastehband2 = new HashSet<dbAsnadDastehband2>();
            this.dbAsnaduplaodfil3 = new HashSet<dbAsnaduplaodfil3>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_ManagerID { get; set; }
        public Nullable<long> ExclusiveCode { get; set; }
        public Nullable<long> RegistrationNumber { get; set; }
        public string CompanyName { get; set; }
        public Nullable<long> Enconomic_Code { get; set; }
        public Nullable<long> Telephone_1 { get; set; }
        public Nullable<long> Telephone_2 { get; set; }
        public Nullable<long> Fax_Number { get; set; }
        public string Url_site { get; set; }
        public Nullable<int> PlaceOfRegister { get; set; }
        public Nullable<int> Company_National_ID { get; set; }
        public string Company_Address { get; set; }
        public string Company_Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FileName { get; set; }
        public string FileSystemName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPeymanContracts> tbPeymanContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPeymanContracts> tbPeymanContracts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPeymanContracts> tbPeymanContracts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserContracts> tbUserContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserContracts> tbUserContracts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadCheack4> dbAsnadCheack4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadDastehband2> dbAsnadDastehband2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnaduplaodfil3> dbAsnaduplaodfil3 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
