//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCreditIndicatorValue
    {
        public int ID { get; set; }
        public Nullable<int> FK_CreditIndicator { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<double> AcceptValue { get; set; }
        public Nullable<double> GoalValue { get; set; }
        public Nullable<double> DoneValue { get; set; }
    
        public virtual tbCreditIndicators tbCreditIndicators { get; set; }
    }
}
