//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcreat_countjob_Fish
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<long> shahr { get; set; }
        public Nullable<long> rostai { get; set; }
        public Nullable<long> chargh { get; set; }
        public Nullable<long> FK_gaval { get; set; }
        public Nullable<long> month { get; set; }
        public Nullable<long> year { get; set; }
        public Nullable<long> sayer { get; set; }
        public Nullable<long> sharh { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
