//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcreat_NameFrml
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbcreat_NameFrml()
        {
            this.tblinK_pymn_frml = new HashSet<tblinK_pymn_frml>();
            this.tbolaviat_frml = new HashSet<tbolaviat_frml>();
            this.tbvalue_frml = new HashSet<tbvalue_frml>();
        }
    
        public long ID { get; set; }
        public string name { get; set; }
        public Nullable<long> shomareh_formol { get; set; }
        public Nullable<System.DateTime> Datatime { get; set; }
        public Nullable<int> usr_sabt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinK_pymn_frml> tblinK_pymn_frml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbolaviat_frml> tbolaviat_frml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbvalue_frml> tbvalue_frml { get; set; }
    }
}
