//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcreatfaal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbcreatfaal()
        {
            this.dbRelatinafrad = new HashSet<dbRelatinafrad>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string sharhasli { get; set; }
        public Nullable<int> numberpayvas { get; set; }
        public Nullable<int> endfalse { get; set; }
        public Nullable<System.DateTime> DataDocument { get; set; }
        public string File_SystemName { get; set; }
        public string File_RealName { get; set; }
        public Nullable<int> imporatant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbRelatinafrad> dbRelatinafrad { get; set; }
    }
}
