//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetermining_creditline
    {
        public int Determining_creditline_ID { get; set; }
        public int FK_creditline { get; set; }
        public Nullable<long> Creditorcredit { get; set; }
        public Nullable<long> Debtorcredit { get; set; }
        public System.DateTime Starttime { get; set; }
        public System.DateTime Endtime { get; set; }
        public int Pyman_ID { get; set; }
        public Nullable<int> elhagh { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCreditIndicators tbCreditIndicators { get; set; }
    }
}
