//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDescriptionDetail
    {
        public int ID { get; set; }
        public Nullable<int> Fk_Description { get; set; }
        public Nullable<long> value { get; set; }
        public string Descriptionn { get; set; }
        public Nullable<int> numbersorat { get; set; }
        public Nullable<bool> type { get; set; }
        public string FileSystemName { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> finalaccept { get; set; }
        public string Titleaccept { get; set; }
    
        public virtual Descriptionsorat Descriptionsorat { get; set; }
    }
}
