//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdetaol
    {
        public int ID { get; set; }
        public Nullable<int> Fk_Pymn { get; set; }
        public Nullable<double> abzarkol { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> number_sorat { get; set; }
        public Nullable<double> mashinkol { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
