//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDocuments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDocuments()
        {
            this.tbExcelDocument = new HashSet<tbExcelDocument>();
            this.tbteaddocument = new HashSet<tbteaddocument>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_PeymanID { get; set; }
        public Nullable<int> TypeOfDocument { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string SooratNumber { get; set; }
        public string SummaryDocument { get; set; }
        public string attachment { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<int> FK_UserID_Saver { get; set; }
        public Nullable<int> FK_DDOfTitle { get; set; }
        public string SummaryDocumentSystemName { get; set; }
        public string attachmentSystemName { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbDocumentsDefinitionOfDocumentTitles tbDocumentsDefinitionOfDocumentTitles { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbExcelDocument> tbExcelDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbteaddocument> tbteaddocument { get; set; }
    }
}
