//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDocumentsDefiOfDoctTitles_Users
    {
        public int ID { get; set; }
        public Nullable<int> FK_DefinitionOfDocTitle { get; set; }
        public Nullable<int> FK_User { get; set; }
        public Nullable<bool> IsSabt { get; set; }
        public Nullable<bool> IsTaeed { get; set; }
    
        public virtual tbDocumentsDefinitionOfDocumentTitles tbDocumentsDefinitionOfDocumentTitles { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
