//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDocumentsDefinitionOfDocumentTitles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDocumentsDefinitionOfDocumentTitles()
        {
            this.tbDocuments = new HashSet<tbDocuments>();
            this.tbDocumentsDefiOfDoctTitles_Users = new HashSet<tbDocumentsDefiOfDoctTitles_Users>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_PeymanID { get; set; }
        public string Title { get; set; }
        public Nullable<int> TypeOfDocument { get; set; }
        public Nullable<int> FK_MoalefeControll { get; set; }
        public Nullable<int> TypeOfControl { get; set; }
        public string Description { get; set; }
        public Nullable<bool> AbleToSetSummery { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocuments> tbDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocumentsDefiOfDoctTitles_Users> tbDocumentsDefiOfDoctTitles_Users { get; set; }
    }
}
