//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipmentMoalefeValue
    {
        public int ID { get; set; }
        public Nullable<double> CountDays { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> FK_Equipment { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> NumberSavedInContracts { get; set; }
        public Nullable<int> NumberSavedInContractsThatAccepted { get; set; }
        public Nullable<bool> accepted { get; set; }
        public Nullable<int> FK_tbEquipmentMoalefeValueReffrenceSave { get; set; }
        public Nullable<int> Fk_user { get; set; }
        public Nullable<int> Fk_pymn { get; set; }
        public Nullable<bool> Final_accept { get; set; }
    
        public virtual tbEquipmentMoalefeValueReffrenceSave tbEquipmentMoalefeValueReffrenceSave { get; set; }
        public virtual tbEquipments tbEquipments { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
