//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEquipments()
        {
            this.tbEquipmentMoalefeValue = new HashSet<tbEquipmentMoalefeValue>();
            this.tbEquipmentSpecificationData = new HashSet<tbEquipmentSpecificationData>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FK_Bunch { get; set; }
        public Nullable<int> FK_Peyman { get; set; }
        public Nullable<long> TotalPrice { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> UnitCount { get; set; }
        public Nullable<long> EachValue { get; set; }
        public string Users { get; set; }
        public Nullable<int> TypeTazmin { get; set; }
        public Nullable<long> TazminPrice { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<int> Count_InQardad { get; set; }
        public Nullable<bool> tersanornottersan { get; set; }
        public Nullable<bool> Rent_or_fuel { get; set; }
        public Nullable<bool> personal { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<double> egareh { get; set; }
        public Nullable<double> Soght { get; set; }
        public Nullable<int> Fk_usr { get; set; }
        public Nullable<double> uniform { get; set; }
        public Nullable<int> model { get; set; }
        public Nullable<int> codtaghiz { get; set; }
    
        public virtual tbEquipmentBunch tbEquipmentBunch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValue> tbEquipmentMoalefeValue { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentSpecificationData> tbEquipmentSpecificationData { get; set; }
    }
}
