//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipmentBunch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEquipmentBunch()
        {
            this.KasriMashin = new HashSet<KasriMashin>();
            this.personalabzar = new HashSet<personalabzar>();
            this.tbEquipments = new HashSet<tbEquipments>();
            this.tbEquipmentSpecifications = new HashSet<tbEquipmentSpecifications>();
            this.tbmarahlsabtbastedit3 = new HashSet<tbmarahlsabtbastedit3>();
        }
    
        public int Eqpbnch_ID { get; set; }
        public string Eqpbnch_Name { get; set; }
        public Nullable<int> FK_EqpgrpID { get; set; }
        public Nullable<int> Eqpbnch_CountFeatures { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KasriMashin> KasriMashin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personalabzar> personalabzar { get; set; }
        public virtual tbEquipmentGroup tbEquipmentGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipments> tbEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentSpecifications> tbEquipmentSpecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahlsabtbastedit3> tbmarahlsabtbastedit3 { get; set; }
    }
}
