//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipmentMoalefeValueReffrenceSave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEquipmentMoalefeValueReffrenceSave()
        {
            this.tbEquipmentMoalefeValue = new HashSet<tbEquipmentMoalefeValue>();
            this.tbEquipmentMoalefeValueReffrenceSave1 = new HashSet<tbEquipmentMoalefeValueReffrenceSave>();
            this.tbEquipmentMoalefeValueReffrenceSave11 = new HashSet<tbEquipmentMoalefeValueReffrenceSave>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> FK_User { get; set; }
        public string FileName { get; set; }
        public string File_SystemName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public Nullable<bool> For_Acceot { get; set; }
        public Nullable<bool> Final_Accept { get; set; }
        public Nullable<int> FK_Baste { get; set; }
        public string File_SystemNameForAccept { get; set; }
        public string FileNameForAccept { get; set; }
        public Nullable<bool> Final_Sabt { get; set; }
        public Nullable<int> is_submit { get; set; }
        public Nullable<int> FK_Basteh { get; set; }
        public Nullable<int> FK_pymn { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> FK_tbmarahesabt4 { get; set; }
        public Nullable<int> FK_tbEquipmentMoalefeValueReffrenceSave { get; set; }
        public Nullable<System.DateTime> Datatmie { get; set; }
        public Nullable<bool> submitt { get; set; }
        public Nullable<bool> del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValue> tbEquipmentMoalefeValue { get; set; }
        public virtual tbCities tbCities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValueReffrenceSave> tbEquipmentMoalefeValueReffrenceSave1 { get; set; }
        public virtual tbEquipmentMoalefeValueReffrenceSave tbEquipmentMoalefeValueReffrenceSave2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValueReffrenceSave> tbEquipmentMoalefeValueReffrenceSave11 { get; set; }
        public virtual tbEquipmentMoalefeValueReffrenceSave tbEquipmentMoalefeValueReffrenceSave3 { get; set; }
        public virtual tbmarahesabt4 tbmarahesabt4 { get; set; }
        public virtual tbmarahlsabtbastedit1 tbmarahlsabtbastedit1 { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbReffrenceSaveLevel tbReffrenceSaveLevel { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
