//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipmentSpecificationData
    {
        public int SpcData_ID { get; set; }
        public Nullable<int> FK_Spec_ID { get; set; }
        public string SpcData { get; set; }
        public Nullable<int> FK_Equipment { get; set; }
    
        public virtual tbEquipments tbEquipments { get; set; }
        public virtual tbEquipmentSpecifications tbEquipmentSpecifications { get; set; }
    }
}
