//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEquipmentSpecifications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEquipmentSpecifications()
        {
            this.tbEquipmentSpecificationData = new HashSet<tbEquipmentSpecificationData>();
        }
    
        public int sp_ID { get; set; }
        public string sp_SpecTitle { get; set; }
        public Nullable<int> FK_EqpBunch_ID { get; set; }
    
        public virtual tbEquipmentBunch tbEquipmentBunch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentSpecificationData> tbEquipmentSpecificationData { get; set; }
    }
}
