//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFormula
    {
        public int FrmI_ID { get; set; }
        public string Frml_Schema { get; set; }
        public string Frml_Title { get; set; }
        public Nullable<int> Frml_Priority { get; set; }
        public string Frml_Formula { get; set; }
        public Nullable<int> FKMoalefeDastMozdi { get; set; }
        public Nullable<bool> Frml_IsActive { get; set; }
        public string Frml_Variablesid { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
    }
}
