//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFucntionExcel
    {
        public int Funcexcl_ID { get; set; }
        public Nullable<int> FK_Basteh { get; set; }
        public Nullable<int> FK_Peyman { get; set; }
        public Nullable<System.DateTime> Funcexcl_DateTime { get; set; }
        public string Funcexcl_ExcelName { get; set; }
        public Nullable<int> FK_UserSubmit { get; set; }
        public Nullable<int> FK_SavedFunction { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbReffrenceSaveLevel tbReffrenceSaveLevel { get; set; }
        public virtual tbSavedFunctions tbSavedFunctions { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
