//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbgozaresh_1275_Fish_estandard
    {
        public long ID { get; set; }
        public string name { get; set; }
        public Nullable<long> startvalue { get; set; }
        public Nullable<long> endvalue { get; set; }
        public Nullable<long> estandard { get; set; }
        public Nullable<long> active { get; set; }
        public Nullable<int> count { get; set; }
        public string type { get; set; }
        public Nullable<int> type_int { get; set; }
    }
}
