//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbgozaresh_1258
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<long> count { get; set; }
        public Nullable<long> active { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public string tarighst { get; set; }
        public string tartughend { get; set; }
        public string type1 { get; set; }
        public string type2 { get; set; }
        public string typer { get; set; }
        public Nullable<long> FK_gozaresh { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
