//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbgozaresh_1275_Fish_filter1
    {
        public long ID { get; set; }
        public Nullable<double> start_val { get; set; }
        public Nullable<double> end_val { get; set; }
        public string name_val { get; set; }
        public Nullable<long> active { get; set; }
    }
}
