//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGOZARESHSAZ1_Creat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBGOZARESHSAZ1_Creat()
        {
            this.TBGOZARESHSAZ2_Creat = new HashSet<TBGOZARESHSAZ2_Creat>();
            this.TBGOZARESHSAZ3_Creat = new HashSet<TBGOZARESHSAZ3_Creat>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public string QURY_SQL { get; set; }
        public string WHERE_IF { get; set; }
        public string SELected { get; set; }
        public Nullable<bool> ACtive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBGOZARESHSAZ2_Creat> TBGOZARESHSAZ2_Creat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBGOZARESHSAZ3_Creat> TBGOZARESHSAZ3_Creat { get; set; }
    }
}
