//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbgozaresh_1275_Fish
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<double> count_darsad { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<long> cout { get; set; }
        public Nullable<long> FK_gozaresh { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<System.DateTime> time2 { get; set; }
        public Nullable<double> moadel { get; set; }
        public Nullable<double> moadelasli { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> active_fal { get; set; }
        public string name { get; set; }
        public Nullable<long> sum_vosol { get; set; }
        public Nullable<long> sum_bedehkar { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
