//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGOZARESHSAZ3_Creat
    {
        public long ID { get; set; }
        public Nullable<long> FK_GOZARSH1 { get; set; }
        public string RADIF { get; set; }
        public string TABLENAEM_RADIF { get; set; }
        public string SOTON { get; set; }
        public string SOTON_NAME { get; set; }
        public string Value { get; set; }
        public string Value_NAME { get; set; }
    
        public virtual TBGOZARESHSAZ1_Creat TBGOZARESHSAZ1_Creat { get; set; }
    }
}
