//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBGOZARESHSAZ2_Creat
    {
        public long ID { get; set; }
        public Nullable<long> FK_GOZARSH1 { get; set; }
        public string SELECTED { get; set; }
        public string Table_NAME { get; set; }
        public Nullable<bool> Active { get; set; }
        public string WHERE_QURY { get; set; }
    
        public virtual TBGOZARESHSAZ1_Creat TBGOZARESHSAZ1_Creat { get; set; }
    }
}
