//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHighLowMoalefeVal
    {
        public int ID { get; set; }
        public Nullable<int> FKUser { get; set; }
        public Nullable<int> FKMoalefe { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> Value { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
