//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHoshdar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbHoshdar()
        {
            this.tbHoshdar1 = new HashSet<tbHoshdar1>();
        }
    
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> typehoshdar { get; set; }
        public string NAME { get; set; }
        public string sharhhoshdar { get; set; }
        public Nullable<int> DOreh { get; set; }
        public Nullable<int> count_dafaat { get; set; }
        public Nullable<System.DateTime> datepickerFromEn_usr { get; set; }
        public Nullable<System.DateTime> datepickerFromEn_usrrepet { get; set; }
        public Nullable<System.DateTime> datepickerFromEn_usrend { get; set; }
        public Nullable<long> ID_ID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Timetamarkoz { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHoshdar1> tbHoshdar1 { get; set; }
    }
}
