//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHoshdar1
    {
        public long ID { get; set; }
        public Nullable<long> FK_tbHoshdar { get; set; }
        public Nullable<int> Dafaat { get; set; }
        public Nullable<int> doreh { get; set; }
        public Nullable<int> Actve { get; set; }
        public Nullable<System.DateTime> Datatime { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<bool> see { get; set; }
    
        public virtual tbHoshdar tbHoshdar { get; set; }
    }
}
