//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbinformation
    {
        public int ID { get; set; }
        public Nullable<bool> Shahri { get; set; }
        public Nullable<bool> rostaeei { get; set; }
        public Nullable<bool> takfaz { get; set; }
        public Nullable<bool> sefaz { get; set; }
        public Nullable<bool> demandi { get; set; }
        public Nullable<bool> fardi { get; set; }
        public Nullable<bool> grohi { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<int> fktitel { get; set; }
    
        public virtual dbTitletahod dbTitletahod { get; set; }
    }
}
