//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbinstallments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbinstallments()
        {
            this.tb_Subset_of_installments = new HashSet<tb_Subset_of_installments>();
        }
    
        public int installment_ID { get; set; }
        public Nullable<int> Peyman_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public int Total_Amount { get; set; }
        public bool Calculation_type { get; set; }
        public string Title { get; set; }
        public string File_SystemName { get; set; }
        public string File_RealName { get; set; }
        public Nullable<int> numberOfInstallment { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<bool> actions { get; set; }
        public Nullable<int> Fk_molfe { get; set; }
        public Nullable<bool> For_Fish { get; set; }
        public Nullable<bool> Action_Fish { get; set; }
        public Nullable<bool> Action_sorat { get; set; }
        public Nullable<bool> Action_traz { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Subset_of_installments> tb_Subset_of_installments { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
