//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbJobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbJobs()
        {
            this.tbRelSystemJob = new HashSet<tbRelSystemJob>();
            this.tbRelUserJob = new HashSet<tbRelUserJob>();
        }
    
        public int jb_ID { get; set; }
        public string jb_Name { get; set; }
        public Nullable<bool> jb_IsActive { get; set; }
        public string jb_Duties { get; set; }
        public string jb_Experience { get; set; }
        public byte[] jb_WorkTime { get; set; }
        public string jb_SafetySkills { get; set; }
        public string jb_SpecializedSkills { get; set; }
        public string jb_GeneralSkills { get; set; }
        public Nullable<int> jb_Gender { get; set; }
        public string jb_Education { get; set; }
        public string jb_GeneralEquipment { get; set; }
        public string jb_SpecializedEquipment { get; set; }
        public string jb_Workspace { get; set; }
        public string jb_Authority { get; set; }
        public string jb_RelatedJobs { get; set; }
        public Nullable<int> jb_ParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRelSystemJob> tbRelSystemJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRelUserJob> tbRelUserJob { get; set; }
    }
}
