//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLink_UserAndAction
    {
        public int UserAction_ID { get; set; }
        public Nullable<int> FK_Action_ID { get; set; }
        public Nullable<int> FK_User_ID { get; set; }
        public Nullable<int> FK_Position_ID { get; set; }
        public bool HasAccess { get; set; }
    
        public virtual tbActions tbActions { get; set; }
        public virtual tbBusinessSide tbBusinessSide { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
