//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblink_moalfe_city
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblink_moalfe_city()
        {
            this.tblink_moalfe_city_valu = new HashSet<tblink_moalfe_city_valu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Fk_pymn { get; set; }
        public Nullable<int> Fk_City { get; set; }
        public Nullable<int> FK_moalfe { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbCities tbCities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblink_moalfe_city_valu> tblink_moalfe_city_valu { get; set; }
    }
}
