//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinK_pymn_frml
    {
        public long ID { get; set; }
        public Nullable<int> FK_pymn { get; set; }
        public Nullable<long> FK_name { get; set; }
        public Nullable<int> shomareh { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbcreat_NameFrml tbcreat_NameFrml { get; set; }
    }
}
