//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLimitation
    {
        public int ID { get; set; }
        public Nullable<double> Limitation_A { get; set; }
        public Nullable<double> Limitation_B { get; set; }
        public Nullable<double> Limitation_C { get; set; }
        public Nullable<double> Limitation_D { get; set; }
        public Nullable<int> FK_pymn { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
