//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLogFunctions
    {
        public int lgfunc_ID { get; set; }
        public Nullable<int> lgfunc_UserID { get; set; }
        public Nullable<System.DateTime> lgfunc_DateTime { get; set; }
        public Nullable<int> lgfunc_MoalefeID { get; set; }
        public Nullable<int> lgfunc_pymnID { get; set; }
        public Nullable<int> lgfunc_BastehID { get; set; }
        public Nullable<double> lgfunc_OldValue { get; set; }
        public Nullable<double> lgfunc_NewValue { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbReffrenceSave tbReffrenceSave { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
