//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmarahlsabtbastedit1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbmarahlsabtbastedit1()
        {
            this.tbEquipmentMoalefeValueReffrenceSave = new HashSet<tbEquipmentMoalefeValueReffrenceSave>();
            this.tbmarahlsabtbastedit2 = new HashSet<tbmarahlsabtbastedit2>();
            this.tbmarahlsabtbastedit3 = new HashSet<tbmarahlsabtbastedit3>();
            this.tbmoalfefishexcel = new HashSet<tbmoalfefishexcel>();
            this.tbSavedFunctions = new HashSet<tbSavedFunctions>();
            this.tbsaveSoratBasteh = new HashSet<tbsaveSoratBasteh>();
        }
    
        public int ID { get; set; }
        public string naem { get; set; }
        public Nullable<int> nameghrogi { get; set; }
        public Nullable<int> nomoalf { get; set; }
        public Nullable<int> Dorehgozaresh { get; set; }
        public Nullable<int> tupeupload { get; set; }
        public Nullable<int> typemoalfeh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValueReffrenceSave> tbEquipmentMoalefeValueReffrenceSave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahlsabtbastedit2> tbmarahlsabtbastedit2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahlsabtbastedit3> tbmarahlsabtbastedit3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoalfefishexcel> tbmoalfefishexcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSavedFunctions> tbSavedFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsaveSoratBasteh> tbsaveSoratBasteh { get; set; }
    }
}
