//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmarahlsabtbastedit5
    {
        public int ID { get; set; }
        public Nullable<int> FK_tbmarahesabt4 { get; set; }
        public string Titel { get; set; }
        public Nullable<bool> value { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual tbmarahesabt4 tbmarahesabt4 { get; set; }
    }
}
