//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmarahlsabtbastedit6
    {
        public int ID { get; set; }
        public Nullable<int> FK_moalfe { get; set; }
        public Nullable<int> FK_moalfeh2 { get; set; }
        public Nullable<int> vaz { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi1 { get; set; }
    }
}
