//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmarahelsabt2
    {
        public long ID { get; set; }
        public Nullable<int> FK_name { get; set; }
        public Nullable<int> FK_moalfe { get; set; }
        public Nullable<bool> del { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbsabtbasteh1 tbsabtbasteh1 { get; set; }
    }
}
