//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmarahlsabtbastedit2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbmarahlsabtbastedit2()
        {
            this.tbmarahesabt4 = new HashSet<tbmarahesabt4>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_City { get; set; }
        public Nullable<int> FK_pymn { get; set; }
        public Nullable<int> FK_namebAST { get; set; }
        public Nullable<bool> Has { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahesabt4> tbmarahesabt4 { get; set; }
        public virtual tbmarahlsabtbastedit1 tbmarahlsabtbastedit1 { get; set; }
        public virtual tbCities tbCities { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
