//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmarhesabt3
    {
        public int ID { get; set; }
        public Nullable<int> marahelsabt { get; set; }
        public Nullable<int> taeed { get; set; }
        public Nullable<int> controlmarahel { get; set; }
    }
}
