//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmoalfehkasri
    {
        public long ID { get; set; }
        public Nullable<int> FK_moalfeh { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<int> active { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
