//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMoalefeValueSorat
    {
        public int mlfvlSorat_ID { get; set; }
        public Nullable<int> FK_Moalefe { get; set; }
        public Nullable<int> FK_Pymn { get; set; }
        public Nullable<double> mlfvlSoat_Value { get; set; }
        public Nullable<int> mlfvlSorat_Year { get; set; }
        public Nullable<int> mlfvlSorat_Month { get; set; }
        public Nullable<bool> mlfvlSorat_Submit { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
