//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMoadelPadashJarimeAyab
    {
        public int ID { get; set; }
        public double Padash { get; set; }
        public double Jarime { get; set; }
        public double AyabOZahab { get; set; }
        public double Moadel { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
