//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmoalfefishexcel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbmoalfefishexcel()
        {
            this.tbMoalefeValueFish = new HashSet<tbMoalefeValueFish>();
            this.tbmoalfefishexcel1 = new HashSet<tbmoalfefishexcel>();
        }
    
        public int ID { get; set; }
        public string Filsesystem { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Fk_Basteh { get; set; }
        public Nullable<int> Fk_Pymn { get; set; }
        public Nullable<int> FK_Basteh1 { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> FK_tbmarahesabt4 { get; set; }
        public Nullable<int> Final_accept { get; set; }
        public Nullable<System.DateTime> Datatmie { get; set; }
        public Nullable<int> FK_tbmoalfefishexcel { get; set; }
        public Nullable<bool> submitt { get; set; }
        public Nullable<int> usr_sabt { get; set; }
        public Nullable<bool> del { get; set; }
        public Nullable<bool> FK_control { get; set; }
        public Nullable<bool> sabtaval { get; set; }
        public Nullable<bool> sabtnahaei { get; set; }
        public Nullable<int> sabt { get; set; }
    
        public virtual tbmarahesabt4 tbmarahesabt4 { get; set; }
        public virtual tbmarahlsabtbastedit1 tbmarahlsabtbastedit1 { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCities tbCities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValueFish> tbMoalefeValueFish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoalfefishexcel> tbmoalfefishexcel1 { get; set; }
        public virtual tbmoalfefishexcel tbmoalfefishexcel2 { get; set; }
        public virtual tbReffrenceSaveLevel tbReffrenceSaveLevel { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
