//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmoshtrak
    {
        public int ID { get; set; }
        public Nullable<double> shahri { get; set; }
        public Nullable<double> rostaei { get; set; }
        public Nullable<double> dfmandi { get; set; }
        public Nullable<int> FK_NAME { get; set; }
    
        public virtual tbNamshnaght tbNamshnaght { get; set; }
    }
}
