//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMoalefeValeFishTest
    {
        public int mlfvlfsh_ID { get; set; }
        public Nullable<int> FK_Moalefe { get; set; }
        public Nullable<int> FK_User { get; set; }
        public Nullable<double> mlfvlfsh_Value { get; set; }
        public Nullable<int> mlfvlfsh_Year { get; set; }
        public Nullable<int> mlfvlfsh_Month { get; set; }
        public Nullable<bool> mlfvlfsh_Submit { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
