//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMoalefeValue
    {
        public int mlfval_ID { get; set; }
        public Nullable<int> mlfval_FKMoalafeDastmozdi { get; set; }
        public Nullable<int> mlfval_FKUser { get; set; }
        public Nullable<int> mlfval_Year { get; set; }
        public Nullable<double> mlfval_Value { get; set; }
        public Nullable<int> mlfval_Month { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
