//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbmoadel_kar2
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> FK_usr_sabt { get; set; }
        public string Fullname { get; set; }
        public Nullable<int> personaID { get; set; }
        public Nullable<int> FK_moalfeh { get; set; }
        public Nullable<int> moalfeh { get; set; }
        public string molafeh_n { get; set; }
        public Nullable<double> megdar { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<double> moadel { get; set; }
        public Nullable<long> fk_moalfeh_fi { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbmadel_kar1 tbmadel_kar1 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
