//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbnergh
    {
        public int ID { get; set; }
        public Nullable<int> FK_name { get; set; }
        public Nullable<double> ghalse { get; set; }
        public Nullable<double> ezafeh { get; set; }
        public Nullable<double> ayab { get; set; }
        public Nullable<double> egareh { get; set; }
        public Nullable<double> abzar { get; set; }
        public Nullable<double> kosorat { get; set; }
        public Nullable<double> sode { get; set; }
        public Nullable<double> saatezafeh { get; set; }
    
        public virtual tbNamshnaght tbNamshnaght { get; set; }
    }
}
