//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNero
    {
        public int ID { get; set; }
        public Nullable<int> FKtitel { get; set; }
        public Nullable<long> value { get; set; }
        public Nullable<long> Estandard { get; set; }
        public Nullable<int> FkTitlerelat { get; set; }
    
        public virtual dbTitletahod dbTitletahod { get; set; }
        public virtual dbTitletahod dbTitletahod1 { get; set; }
    }
}
