//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNergh_Pymn
    {
        public int ID { get; set; }
        public Nullable<int> FK_Pymn { get; set; }
        public Nullable<double> nergh { get; set; }
        public Nullable<long> numbersorat { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
