//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbolaviat_frml
    {
        public long ID { get; set; }
        public Nullable<long> FK_name_frml { get; set; }
        public Nullable<long> olaviat { get; set; }
        public Nullable<long> vorodi { get; set; }
        public Nullable<long> ghorogi { get; set; }
        public Nullable<int> FK_frml { get; set; }
        public Nullable<System.DateTime> Datatime { get; set; }
        public Nullable<int> usr_sabt { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbcreat_NameFrml tbcreat_NameFrml { get; set; }
    }
}
