//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPeymanZaribForFish
    {
        public int pymnzrbfsh_ID { get; set; }
        public Nullable<double> pymnzrbfsh_zaribkasrekar { get; set; }
        public Nullable<int> FKPeyman { get; set; }
        public Nullable<double> pymnzrbfsh_zaribmamoriat { get; set; }
        public Nullable<double> pymnzrbfsh_zaribqeybat { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
