//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPeymanContracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPeymanContracts()
        {
            this.Link_User_And_Peyman = new HashSet<Link_User_And_Peyman>();
            this.tbcountpymnmoqym = new HashSet<tbcountpymnmoqym>();
            this.tbEquipmentMoalefeValue = new HashSet<tbEquipmentMoalefeValue>();
            this.tbEquipmentMoalefeValueReffrenceSave = new HashSet<tbEquipmentMoalefeValueReffrenceSave>();
            this.tbEquipments = new HashSet<tbEquipments>();
            this.tbFucntionExcel = new HashSet<tbFucntionExcel>();
            this.tbkasrikarkonanpy = new HashSet<tbkasrikarkonanpy>();
            this.tbLimitation = new HashSet<tbLimitation>();
            this.tbmarahlsabtbastedit2 = new HashSet<tbmarahlsabtbastedit2>();
            this.tbNergh_Pymn = new HashSet<tbNergh_Pymn>();
            this.tbPeymanContractPrice = new HashSet<tbPeymanContractPrice>();
            this.dbAsnaduplaodfil3 = new HashSet<dbAsnaduplaodfil3>();
            this.dbtarifmahdodayt5 = new HashSet<dbtarifmahdodayt5>();
            this.dbtitlesor = new HashSet<dbtitlesor>();
            this.dbzaribshogl = new HashSet<dbzaribshogl>();
            this.Descriptionsorat = new HashSet<Descriptionsorat>();
            this.FinancialDocuments = new HashSet<FinancialDocuments>();
            this.KasriMashin = new HashSet<KasriMashin>();
            this.personalabzar = new HashSet<personalabzar>();
            this.tbRial_restrictions_pymn = new HashSet<tbRial_restrictions_pymn>();
            this.tbSoratvaziat = new HashSet<tbSoratvaziat>();
            this.tbDocumentsAuthorizedUsers = new HashSet<tbDocumentsAuthorizedUsers>();
            this.tbCommodityProject = new HashSet<tbCommodityProject>();
            this.tbPeymanZaribForFish = new HashSet<tbPeymanZaribForFish>();
            this.tbControllyPeyman = new HashSet<tbControllyPeyman>();
            this.tbdetaol = new HashSet<tbdetaol>();
            this.tbDetermining_creditline = new HashSet<tbDetermining_creditline>();
            this.tbDocuments = new HashSet<tbDocuments>();
            this.tbDocumentsDefinitionOfDocumentTitles = new HashSet<tbDocumentsDefinitionOfDocumentTitles>();
            this.tbFinalCheckSoorat = new HashSet<tbFinalCheckSoorat>();
            this.tbFinantialStatements = new HashSet<tbFinantialStatements>();
            this.tbinstallments = new HashSet<tbinstallments>();
            this.tbkasriabzar = new HashSet<tbkasriabzar>();
            this.tblinK_pymn_frml = new HashSet<tblinK_pymn_frml>();
            this.tbLogFunctions = new HashSet<tbLogFunctions>();
            this.tbMoalefeValuePishkhan = new HashSet<tbMoalefeValuePishkhan>();
            this.tbMoalefeValueSorat = new HashSet<tbMoalefeValueSorat>();
            this.tbmoalfefishexcel = new HashSet<tbmoalfefishexcel>();
            this.tbolaviatsabad = new HashSet<tbolaviatsabad>();
            this.tbpeymancities = new HashSet<tbpeymancities>();
            this.tbPeymanContractsZarib = new HashSet<tbPeymanContractsZarib>();
            this.tbPeymanElhaghie = new HashSet<tbPeymanElhaghie>();
            this.tbpeymaninformatio = new HashSet<tbpeymaninformatio>();
            this.tbReffrenceAccept = new HashSet<tbReffrenceAccept>();
            this.tbReffrenceSave = new HashSet<tbReffrenceSave>();
            this.tbRemindsoratvazi = new HashSet<tbRemindsoratvazi>();
            this.tbsabtbasteh1 = new HashSet<tbsabtbasteh1>();
            this.tbSavedFunctions = new HashSet<tbSavedFunctions>();
            this.tbsaveSoratBasteh = new HashSet<tbsaveSoratBasteh>();
            this.tbSoratSalaryDetail = new HashSet<tbSoratSalaryDetail>();
            this.tbvalue_frml = new HashSet<tbvalue_frml>();
            this.tbvaziat_mahdodayt = new HashSet<tbvaziat_mahdodayt>();
            this.tbVosoolMotalebat = new HashSet<tbVosoolMotalebat>();
            this.vaziatsoratvaziat = new HashSet<vaziatsoratvaziat>();
        }
    
        public int pec_ID { get; set; }
        public string pec_Title { get; set; }
        public Nullable<bool> pec_TypeOfContract { get; set; }
        public string pec_Price { get; set; }
        public Nullable<int> FK_KarfarmaID { get; set; }
        public Nullable<System.DateTime> pec_StartTime { get; set; }
        public Nullable<System.DateTime> pec_EndTime { get; set; }
        public string pec_ContractNumber { get; set; }
        public Nullable<int> pec_ProjectCode { get; set; }
        public string pec_FileName { get; set; }
        public string pec_FileSystemName { get; set; }
        public Nullable<bool> pec_IsElhaghie { get; set; }
        public Nullable<int> FK_PecFatherElhaghie { get; set; }
        public Nullable<int> FK_UserDastGahNezarati { get; set; }
        public Nullable<int> FK_UserTarafDovvom { get; set; }
        public string pec_BriefTitle { get; set; }
        public Nullable<bool> Inactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link_User_And_Peyman> Link_User_And_Peyman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbcountpymnmoqym> tbcountpymnmoqym { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValue> tbEquipmentMoalefeValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValueReffrenceSave> tbEquipmentMoalefeValueReffrenceSave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipments> tbEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFucntionExcel> tbFucntionExcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbkasrikarkonanpy> tbkasrikarkonanpy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLimitation> tbLimitation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahlsabtbastedit2> tbmarahlsabtbastedit2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbNergh_Pymn> tbNergh_Pymn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPeymanContractPrice> tbPeymanContractPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnaduplaodfil3> dbAsnaduplaodfil3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtarifmahdodayt5> dbtarifmahdodayt5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtitlesor> dbtitlesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbzaribshogl> dbzaribshogl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Descriptionsorat> Descriptionsorat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialDocuments> FinancialDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KasriMashin> KasriMashin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personalabzar> personalabzar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRial_restrictions_pymn> tbRial_restrictions_pymn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSoratvaziat> tbSoratvaziat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocumentsAuthorizedUsers> tbDocumentsAuthorizedUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCommodityProject> tbCommodityProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPeymanZaribForFish> tbPeymanZaribForFish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbControllyPeyman> tbControllyPeyman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbdetaol> tbdetaol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetermining_creditline> tbDetermining_creditline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocuments> tbDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocumentsDefinitionOfDocumentTitles> tbDocumentsDefinitionOfDocumentTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFinalCheckSoorat> tbFinalCheckSoorat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFinantialStatements> tbFinantialStatements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbinstallments> tbinstallments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbkasriabzar> tbkasriabzar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinK_pymn_frml> tblinK_pymn_frml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLogFunctions> tbLogFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValuePishkhan> tbMoalefeValuePishkhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValueSorat> tbMoalefeValueSorat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoalfefishexcel> tbmoalfefishexcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbolaviatsabad> tbolaviatsabad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbpeymancities> tbpeymancities { get; set; }
        public virtual tbCompanies tbCompanies { get; set; }
        public virtual tbCompanies tbCompanies1 { get; set; }
        public virtual tbCompanies tbCompanies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPeymanContractsZarib> tbPeymanContractsZarib { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPeymanElhaghie> tbPeymanElhaghie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbpeymaninformatio> tbpeymaninformatio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceAccept> tbReffrenceAccept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceSave> tbReffrenceSave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRemindsoratvazi> tbRemindsoratvazi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsabtbasteh1> tbsabtbasteh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSavedFunctions> tbSavedFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsaveSoratBasteh> tbsaveSoratBasteh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSoratSalaryDetail> tbSoratSalaryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbvalue_frml> tbvalue_frml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbvaziat_mahdodayt> tbvaziat_mahdodayt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbVosoolMotalebat> tbVosoolMotalebat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaziatsoratvaziat> vaziatsoratvaziat { get; set; }
    }
}
