//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpeymaninformatio
    {
        public int ID { get; set; }
        public Nullable<int> numbersorat { get; set; }
        public Nullable<int> Fk_pymn { get; set; }
        public Nullable<double> hosin { get; set; }
        public Nullable<double> jari { get; set; }
        public Nullable<double> sarmayi { get; set; }
        public Nullable<int> moshtrakin { get; set; }
        public Nullable<double> bemeh { get; set; }
        public Nullable<bool> accept { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
