//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPeymanContractsZarib
    {
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> FK_CreditIndicators { get; set; }
        public Nullable<int> FK_Peyman { get; set; }
        public string Value { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCreditIndicators tbCreditIndicators { get; set; }
    }
}
