//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPeymanContractPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPeymanContractPrice()
        {
            this.tbSoratSavefromExcelMoalfe = new HashSet<tbSoratSavefromExcelMoalfe>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FKPeymanID { get; set; }
        public string Unit { get; set; }
        public string UnitTitle { get; set; }
        public Nullable<System.DateTime> DateOccured { get; set; }
        public Nullable<bool> IsElhaghie { get; set; }
        public string Price { get; set; }
        public Nullable<int> Count { get; set; }
        public string CountForPer { get; set; }
        public Nullable<int> ElahghieCount { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSoratSavefromExcelMoalfe> tbSoratSavefromExcelMoalfe { get; set; }
    }
}
