//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPeymanElhaghie
    {
        public int ID { get; set; }
        public Nullable<int> FK_PeymanID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Price { get; set; }
        public Nullable<bool> IsLower { get; set; }
        public Nullable<double> CountForPer { get; set; }
        public Nullable<double> Count { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
