//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbresultpishkansehnaght
    {
        public int ID { get; set; }
        public Nullable<int> FK_NAME { get; set; }
        public Nullable<int> count_person { get; set; }
        public Nullable<int> count_tagsoso_littel { get; set; }
        public Nullable<double> persent_tagsoso_littel { get; set; }
        public Nullable<double> persent_person_tavarom { get; set; }
        public Nullable<int> count_person_tavarom { get; set; }
        public Nullable<double> persent_person_jobran { get; set; }
        public Nullable<int> count_person_jobran { get; set; }
        public Nullable<int> count_need_person { get; set; }
        public Nullable<double> Condition1_mojod { get; set; }
        public Nullable<double> Condition1_jobran { get; set; }
        public Nullable<double> Condition1_beheneh { get; set; }
        public Nullable<double> Condition2_mojod { get; set; }
        public Nullable<double> Condition2_jobran { get; set; }
        public Nullable<double> Condition2_beheneh { get; set; }
        public Nullable<double> Condition2_edehal { get; set; }
        public Nullable<double> Condition1_edehal { get; set; }
    
        public virtual tbNamshnaght tbNamshnaght { get; set; }
    }
}
