//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReffrenceAccept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbReffrenceAccept()
        {
            this.tbReffrenceAcceptLevel = new HashSet<tbReffrenceAcceptLevel>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_PeymanID { get; set; }
        public Nullable<int> FK_ReffrenceSaveLevel { get; set; }
        public Nullable<int> MaxDaysForAccept { get; set; }
        public Nullable<int> CountLevels { get; set; }
        public Nullable<int> EndDayAllLevels { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbReffrenceSaveLevel tbReffrenceSaveLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceAcceptLevel> tbReffrenceAcceptLevel { get; set; }
    }
}
