//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRelUserJob
    {
        public int ruj_ID { get; set; }
        public Nullable<int> FK_jbID { get; set; }
        public Nullable<int> FK_userID { get; set; }
    
        public virtual tbJobs tbJobs { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
