//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReffrenceSave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbReffrenceSave()
        {
            this.tbLogFunctions = new HashSet<tbLogFunctions>();
            this.tbReffrenceSaveLevel = new HashSet<tbReffrenceSaveLevel>();
            this.tbReffrenceSaveLevelMoalefe = new HashSet<tbReffrenceSaveLevelMoalefe>();
            this.tbReffrenceSaveLevelUser = new HashSet<tbReffrenceSaveLevelUser>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_PeymanID { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> TypeOfUpload { get; set; }
        public Nullable<int> MaxDaysForSave { get; set; }
        public Nullable<int> CountLevels { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> TypeOfUser { get; set; }
        public Nullable<int> IsFor { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLogFunctions> tbLogFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceSaveLevel> tbReffrenceSaveLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceSaveLevelMoalefe> tbReffrenceSaveLevelMoalefe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceSaveLevelUser> tbReffrenceSaveLevelUser { get; set; }
    }
}
