//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReffrenceSaveLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbReffrenceSaveLevel()
        {
            this.tbEquipmentMoalefeValueReffrenceSave = new HashSet<tbEquipmentMoalefeValueReffrenceSave>();
            this.tbFucntionExcel = new HashSet<tbFucntionExcel>();
            this.tbmoalfefishexcel = new HashSet<tbmoalfefishexcel>();
            this.tbSavedFunctions = new HashSet<tbSavedFunctions>();
            this.tbsaveSoratBasteh = new HashSet<tbsaveSoratBasteh>();
            this.tbReffrenceAccept = new HashSet<tbReffrenceAccept>();
            this.tbReffrenceSaveLevelMoalefe = new HashSet<tbReffrenceSaveLevelMoalefe>();
            this.tbReffrenceSaveLevelUser = new HashSet<tbReffrenceSaveLevelUser>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_RRSave { get; set; }
        public string Title { get; set; }
        public Nullable<int> StartDaysInMonth { get; set; }
        public Nullable<int> DeadLine { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public System.DateTime Data_time_create { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValueReffrenceSave> tbEquipmentMoalefeValueReffrenceSave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFucntionExcel> tbFucntionExcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoalfefishexcel> tbmoalfefishexcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSavedFunctions> tbSavedFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsaveSoratBasteh> tbsaveSoratBasteh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceAccept> tbReffrenceAccept { get; set; }
        public virtual tbReffrenceSave tbReffrenceSave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceSaveLevelMoalefe> tbReffrenceSaveLevelMoalefe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceSaveLevelUser> tbReffrenceSaveLevelUser { get; set; }
    }
}
