//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRial_restrictions_pymn
    {
        public int ID { get; set; }
        public Nullable<int> Fk_pymn { get; set; }
        public Nullable<double> restrictions_A { get; set; }
        public Nullable<double> restrictions_B { get; set; }
        public Nullable<double> restrictions_C { get; set; }
        public Nullable<double> restrictions_D { get; set; }
        public Nullable<double> mahdodatmogym_B { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
