//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSaleryIsCalculated
    {
        public int slrcal_ID { get; set; }
        public Nullable<int> slrcal_Month { get; set; }
        public Nullable<int> slrcal_Year { get; set; }
        public Nullable<int> FKUser { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
