//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSabtEstedadKhodro
    {
        public long ID { get; set; }
        public Nullable<long> FK_ { get; set; }
        public Nullable<int> VaziatHozor { get; set; }
        public Nullable<long> Kilometr { get; set; }
        public Nullable<int> NoeAmaliat { get; set; }
        public Nullable<int> VaziatKhodro { get; set; }
        public Nullable<long> NoeEyb { get; set; }
        public string Sharh { get; set; }
        public string SaatShoro { get; set; }
        public string SaatKhateme { get; set; }
        public Nullable<System.DateTime> SaatShoro1 { get; set; }
        public Nullable<System.DateTime> SaatKhateme1 { get; set; }
        public Nullable<int> UserSabt { get; set; }
        public Nullable<System.DateTime> TarikhSabt { get; set; }
    
        public virtual createmoshkelmashin createmoshkelmashin { get; set; }
        public virtual Table_Khodro Table_Khodro { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
