//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSavedFunctions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSavedFunctions()
        {
            this.tbFucntionExcel = new HashSet<tbFucntionExcel>();
            this.tbMoalefeDastmozdiValueFromExcel = new HashSet<tbMoalefeDastmozdiValueFromExcel>();
            this.tbSavedFunctions1 = new HashSet<tbSavedFunctions>();
        }
    
        public int svdfunc_ID { get; set; }
        public Nullable<int> svdfunc_UserSaveID { get; set; }
        public Nullable<System.DateTime> svdfunc_SavedDateTime { get; set; }
        public Nullable<System.DateTime> svdfunc_FromDate { get; set; }
        public Nullable<System.DateTime> svdfunc_ToDate { get; set; }
        public Nullable<int> svdfunc_BastehID { get; set; }
        public Nullable<int> svdfunc_pymnID { get; set; }
        public Nullable<bool> svdfunc_IsSubmmit { get; set; }
        public string svdfunc_FileSystemName { get; set; }
        public string svdfunc_FileName { get; set; }
        public Nullable<bool> For_Accept { get; set; }
        public Nullable<bool> Final_Accept { get; set; }
        public Nullable<bool> Final_Sabt { get; set; }
        public string svdfunc_FileSystemNameExcel { get; set; }
        public string svdfunc_FileNameExcel { get; set; }
        public Nullable<int> FK_Basteh { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> FK_tbmarahesabt4 { get; set; }
        public Nullable<int> FK_tbSavedFunctions { get; set; }
        public Nullable<System.DateTime> Datatmie { get; set; }
        public Nullable<bool> submitt { get; set; }
        public Nullable<bool> del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFucntionExcel> tbFucntionExcel { get; set; }
        public virtual tbmarahesabt4 tbmarahesabt4 { get; set; }
        public virtual tbmarahlsabtbastedit1 tbmarahlsabtbastedit1 { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCities tbCities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeDastmozdiValueFromExcel> tbMoalefeDastmozdiValueFromExcel { get; set; }
        public virtual tbReffrenceSaveLevel tbReffrenceSaveLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSavedFunctions> tbSavedFunctions1 { get; set; }
        public virtual tbSavedFunctions tbSavedFunctions2 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
