//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsabtbasteh1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbsabtbasteh1()
        {
            this.tbmarahelsabt2 = new HashSet<tbmarahelsabt2>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FK_pymn { get; set; }
        public Nullable<int> FK_city { get; set; }
        public string namebasteh { get; set; }
        public Nullable<int> fishorsorat { get; set; }
        public Nullable<int> taghiozat { get; set; }
    
        public virtual tbEquipmentGroup tbEquipmentGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahelsabt2> tbmarahelsabt2 { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCities tbCities { get; set; }
    }
}
