//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsaveSoratBasteh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbsaveSoratBasteh()
        {
            this.tbSoratSavefromExcelMoalfe = new HashSet<tbSoratSavefromExcelMoalfe>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Todata { get; set; }
        public Nullable<System.DateTime> Fromdata { get; set; }
        public Nullable<int> Fk_usrsave { get; set; }
        public Nullable<int> fk_Basteh { get; set; }
        public Nullable<int> fk_pymn { get; set; }
        public Nullable<bool> ISsubmit { get; set; }
        public string FileSystemName { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> For_Accept { get; set; }
        public Nullable<bool> Final_Accept { get; set; }
        public Nullable<bool> Final_sabt { get; set; }
        public Nullable<System.DateTime> Data_time { get; set; }
        public string FileSystemName_pavast { get; set; }
        public string FileName_pavast { get; set; }
        public Nullable<System.DateTime> Data_time_edit { get; set; }
        public Nullable<int> FK_Bastehedit { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> FK_tbmarahesabt4 { get; set; }
        public Nullable<bool> submitt { get; set; }
        public Nullable<bool> del { get; set; }
    
        public virtual tbmarahesabt4 tbmarahesabt4 { get; set; }
        public virtual tbmarahlsabtbastedit1 tbmarahlsabtbastedit1 { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCities tbCities { get; set; }
        public virtual tbReffrenceSaveLevel tbReffrenceSaveLevel { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSoratSavefromExcelMoalfe> tbSoratSavefromExcelMoalfe { get; set; }
    }
}
