//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSetting_Sell_Create
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserTitle { get; set; }
        public string UserImage { get; set; }
        public string Password1 { get; set; }
        public string NameSoftwar { get; set; }
        public string VersionSoftwar { get; set; }
        public Nullable<System.DateTime> DateSell { get; set; }
        public Nullable<System.DateTime> DateSuport { get; set; }
        public string Password2 { get; set; }
    }
}
