//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSheetsExtracted
    {
        public int ID { get; set; }
        public string NameSaved { get; set; }
        public string SheetName { get; set; }
        public Nullable<bool> IsReport { get; set; }
        public string SheetContent { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> ColumnCount { get; set; }
        public Nullable<int> roowCount { get; set; }
    }
}
