//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsherkatpyam
    {
        public int ID { get; set; }
        public Nullable<int> FK_usr1 { get; set; }
        public Nullable<int> FK_isr2 { get; set; }
        public string Title { get; set; }
        public string File_SystemName { get; set; }
        public string File_RealName { get; set; }
        public Nullable<int> FK_RELATIONPERSON { get; set; }
        public Nullable<int> Fk_afrad { get; set; }
        public Nullable<System.DateTime> DataDocument { get; set; }
        public Nullable<int> notseee { get; set; }
    
        public virtual tbperson tbperson { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        public virtual tbUsers tbUsers1 { get; set; }
    }
}
