//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbshaghes
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FK_name { get; set; }
        public string Title { get; set; }
        public Nullable<double> value { get; set; }
        public string vahed { get; set; }
    
        public virtual tbNamshnaght tbNamshnaght { get; set; }
    }
}
