//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSoratvaziat
    {
        public int ID { get; set; }
        public Nullable<int> FK_Sabad { get; set; }
        public Nullable<int> Fk_pymn { get; set; }
        public Nullable<int> number_sorat { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<long> Enerjy { get; set; }
        public Nullable<double> nergh { get; set; }
        public Nullable<long> gham { get; set; }
        public Nullable<long> value { get; set; }
        public Nullable<long> Finalvaluesorat { get; set; }
        public Nullable<bool> Final_accept { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<long> eydipadash { get; set; }
        public Nullable<double> jaremeh { get; set; }
        public Nullable<double> jaremeh2 { get; set; }
        public Nullable<double> padash { get; set; }
        public Nullable<double> padash2 { get; set; }
        public Nullable<int> fk_city { get; set; }
        public Nullable<long> bemetakmilcol { get; set; }
        public Nullable<long> moraghaSIKOL { get; set; }
        public Nullable<long> savesoratvaziat { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCities tbCities { get; set; }
        public virtual tbCreditIndicators tbCreditIndicators { get; set; }
    }
}
