//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSoratSavefromExcelMoalfe
    {
        public int ID { get; set; }
        public Nullable<int> FK_MoalfeDastmozdi { get; set; }
        public Nullable<int> FK_city { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> FK_SavedFunctionsID { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> varpymn { get; set; }
        public Nullable<int> FK_price { get; set; }
        public Nullable<double> valuenergh { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbPeymanContractPrice tbPeymanContractPrice { get; set; }
        public virtual tbCities tbCities { get; set; }
        public virtual tbsaveSoratBasteh tbsaveSoratBasteh { get; set; }
    }
}
