//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSuggestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSuggestion()
        {
            this.tbSuggestion1 = new HashSet<tbSuggestion>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsSuggest { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string FileSystemName { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> FKParentID { get; set; }
        public Nullable<bool> IsSeen { get; set; }
        public Nullable<int> FK_UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSuggestion> tbSuggestion1 { get; set; }
        public virtual tbSuggestion tbSuggestion2 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
