//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSuggestion_Admin
    {
        public long ID { get; set; }
        public Nullable<int> FK_usrsabt { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<System.DateTime> timesabt { get; set; }
        public string FileSystemName { get; set; }
        public string FileName { get; set; }
        public string fullnamesabt { get; set; }
        public string Title { get; set; }
        public string personalsabt { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
