//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbtatialtmoadel
    {
        public long ID { get; set; }
        public Nullable<long> friday { get; set; }
        public Nullable<long> notfriday { get; set; }
        public Nullable<long> ghas { get; set; }
        public Nullable<int> rozmonth { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> khales { get; set; }
    }
}
