//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTarifAbzarKar1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTarifAbzarKar1()
        {
            this.tbTarifAbzarKar2Estedad = new HashSet<tbTarifAbzarKar2Estedad>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Vahed { get; set; }
        public Nullable<System.DateTime> TimeSabt { get; set; }
        public Nullable<long> UserSabt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTarifAbzarKar2Estedad> tbTarifAbzarKar2Estedad { get; set; }
    }
}
