//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTarifAbzarKar2Estedad
    {
        public long ID { get; set; }
        public Nullable<long> Fk_tarifabzarkar { get; set; }
        public Nullable<int> SalemZakhire { get; set; }
        public Nullable<int> SalemMamor { get; set; }
        public Nullable<int> NiyazmandTamir { get; set; }
        public Nullable<int> GomShode { get; set; }
        public Nullable<int> jam { get; set; }
        public string Sharh { get; set; }
        public Nullable<System.DateTime> TimeSabt { get; set; }
        public Nullable<long> UserSabt { get; set; }
    
        public virtual tbTarifAbzarKar1 tbTarifAbzarKar1 { get; set; }
    }
}
