//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTarifKalayeAsasi2Estedad
    {
        public long ID { get; set; }
        public Nullable<long> Fk_TarifKalayeAsasi { get; set; }
        public Nullable<int> DarAnbar { get; set; }
        public Nullable<int> nazdMamor { get; set; }
        public Nullable<int> Jam { get; set; }
        public string Sharh { get; set; }
        public Nullable<System.DateTime> TimeSabt { get; set; }
        public Nullable<long> UserSabt { get; set; }
    
        public virtual tbTarifKalayeAsasi1 tbTarifKalayeAsasi1 { get; set; }
    }
}
