//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbteaddocument
    {
        public int ID { get; set; }
        public Nullable<int> Fk_Document { get; set; }
        public string Title { get; set; }
        public Nullable<long> valuetaead { get; set; }
    
        public virtual tbDocuments tbDocuments { get; set; }
    }
}
