//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUnitParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUnitParameter()
        {
            this.tbContractMoalefeDastmozdi = new HashSet<tbContractMoalefeDastmozdi>();
            this.dbAsnadcratname = new HashSet<dbAsnadcratname>();
        }
    
        public int unt_ID { get; set; }
        public string unt_Name { get; set; }
        public string unt_abbrevation { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbContractMoalefeDastmozdi> tbContractMoalefeDastmozdi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadcratname> dbAsnadcratname { get; set; }
    }
}
