//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserRentContracts
    {
        public int urc_ID { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<int> FK_TenantID { get; set; }
        public string urc_Subject { get; set; }
        public string urc_Tajhizat { get; set; }
        public string urc_NumberPlates { get; set; }
        public string urc_CardNumber { get; set; }
        public string urc_MelakeMohasebe { get; set; }
        public Nullable<System.DateTime> urc_StartDate { get; set; }
        public Nullable<System.DateTime> urc_EndDate { get; set; }
        public Nullable<int> urc_totalMonth { get; set; }
        public Nullable<long> urc_PayAble { get; set; }
        public Nullable<long> urc_payMonth { get; set; }
        public string urc_FileName { get; set; }
        public Nullable<bool> urc_Accepted { get; set; }
        public string urc_FileSystemName { get; set; }
    }
}
