//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsers()
        {
            this.Link_User_And_Moalefe = new HashSet<Link_User_And_Moalefe>();
            this.Link_User_And_Peyman = new HashSet<Link_User_And_Peyman>();
            this.tbContractJobGroup = new HashSet<tbContractJobGroup>();
            this.tbEquipmentMoalefeValue = new HashSet<tbEquipmentMoalefeValue>();
            this.tbEquipmentMoalefeValueReffrenceSave = new HashSet<tbEquipmentMoalefeValueReffrenceSave>();
            this.tbEquipments = new HashSet<tbEquipments>();
            this.tbFucntionExcel = new HashSet<tbFucntionExcel>();
            this.tbmarahesabt4 = new HashSet<tbmarahesabt4>();
            this.tbUserContracts = new HashSet<tbUserContracts>();
            this.tbvaziat_mahdodayt = new HashSet<tbvaziat_mahdodayt>();
            this.arzyzbi1 = new HashSet<arzyzbi1>();
            this.arzyzbi2_soal = new HashSet<arzyzbi2_soal>();
            this.arzyzbi3_gozeneh = new HashSet<arzyzbi3_gozeneh>();
            this.arzyzbi4_link = new HashSet<arzyzbi4_link>();
            this.arzyzbi5_time = new HashSet<arzyzbi5_time>();
            this.arzyzbi6_value = new HashSet<arzyzbi6_value>();
            this.arzyzbi7_value_usr = new HashSet<arzyzbi7_value_usr>();
            this.arzyzbi8_edit = new HashSet<arzyzbi8_edit>();
            this.BaleLinkRequests = new HashSet<BaleLinkRequests>();
            this.closed_time_estedad = new HashSet<closed_time_estedad>();
            this.ControlVersions = new HashSet<ControlVersions>();
            this.Create_linkmamorjob_4 = new HashSet<Create_linkmamorjob_4>();
            this.dbAsnadCheack4 = new HashSet<dbAsnadCheack4>();
            this.dbAsnadcratasnad = new HashSet<dbAsnadcratasnad>();
            this.dbAsnadDastehband2 = new HashSet<dbAsnadDastehband2>();
            this.dbAsnadsalvorodi = new HashSet<dbAsnadsalvorodi>();
            this.dbAsnaduplaodfil3 = new HashSet<dbAsnaduplaodfil3>();
            this.dbdashbord1 = new HashSet<dbdashbord1>();
            this.dbdashbordmamor = new HashSet<dbdashbordmamor>();
            this.dberganametanble2_2 = new HashSet<dberganametanble2_2>();
            this.dbergapilike = new HashSet<dbergapilike>();
            this.dbergha2 = new HashSet<dbergha2>();
            this.dbergha6 = new HashSet<dbergha6>();
            this.dbergharel_4 = new HashSet<dbergharel_4>();
            this.dbergharel2_3 = new HashSet<dbergharel2_3>();
            this.dbergharel4_5 = new HashSet<dbergharel4_5>();
            this.dbergharelicratgroup_8 = new HashSet<dbergharelicratgroup_8>();
            this.dbergharelicratgrouprel11 = new HashSet<dbergharelicratgrouprel11>();
            this.dbergharelicratgrouprel8_9 = new HashSet<dbergharelicratgrouprel8_9>();
            this.dbergharelicreatejob13 = new HashSet<dbergharelicreatejob13>();
            this.dbergharelimsertfk1_7 = new HashSet<dbergharelimsertfk1_7>();
            this.dbergharelinsert_6 = new HashSet<dbergharelinsert_6>();
            this.dberja = new HashSet<dberja>();
            this.dbGIS_USR = new HashSet<dbGIS_USR>();
            this.dbGIS_USR_after = new HashSet<dbGIS_USR_after>();
            this.dblog = new HashSet<dblog>();
            this.dbmovazafisabt = new HashSet<dbmovazafisabt>();
            this.dbRelatinafrad = new HashSet<dbRelatinafrad>();
            this.dbrelatinperson = new HashSet<dbrelatinperson>();
            this.dbsathdastressi4 = new HashSet<dbsathdastressi4>();
            this.dbtarifmovazaf = new HashSet<dbtarifmovazaf>();
            this.dbtarifvazifehasli = new HashSet<dbtarifvazifehasli>();
            this.dbvaziathozor = new HashSet<dbvaziathozor>();
            this.erja_like = new HashSet<erja_like>();
            this.erja_sabt_usr = new HashSet<erja_sabt_usr>();
            this.estedad_khodro = new HashSet<estedad_khodro>();
            this.EstedadNiroEnsani = new HashSet<EstedadNiroEnsani>();
            this.FinancialDocuments = new HashSet<FinancialDocuments>();
            this.madarek_1 = new HashSet<madarek_1>();
            this.madarek_linkcheack_2 = new HashSet<madarek_linkcheack_2>();
            this.madarek_linkesabt_3 = new HashSet<madarek_linkesabt_3>();
            this.madarek_sabtdoreh_4 = new HashSet<madarek_sabtdoreh_4>();
            this.madarek_vaziatdoreh_5 = new HashSet<madarek_vaziatdoreh_5>();
            this.NatigeEshterakBala50 = new HashSet<NatigeEshterakBala50>();
            this.Table_Khodro = new HashSet<Table_Khodro>();
            this.Table_Khodro1 = new HashSet<Table_Khodro>();
            this.Table_Khodro2 = new HashSet<Table_Khodro>();
            this.Table_Khodro3 = new HashSet<Table_Khodro>();
            this.tbAdamAdam = new HashSet<tbAdamAdam>();
            this.tbAdamAdam1 = new HashSet<tbAdamAdam>();
            this.tbAdamShahr = new HashSet<tbAdamShahr>();
            this.tbcount_car = new HashSet<tbcount_car>();
            this.tbDocuments = new HashSet<tbDocuments>();
            this.tbExcelDocument = new HashSet<tbExcelDocument>();
            this.tbgozaresh_1258 = new HashSet<tbgozaresh_1258>();
            this.tbHoshdar = new HashSet<tbHoshdar>();
            this.tbinstallments = new HashSet<tbinstallments>();
            this.tbperson = new HashSet<tbperson>();
            this.tbSabtEstedadKhodro = new HashSet<tbSabtEstedadKhodro>();
            this.tbsherkatpyam = new HashSet<tbsherkatpyam>();
            this.tbsherkatpyam1 = new HashSet<tbsherkatpyam>();
            this.tbSuggestion = new HashSet<tbSuggestion>();
            this.tbSuggestion_Admin = new HashSet<tbSuggestion_Admin>();
            this.tbvalue_frml = new HashSet<tbvalue_frml>();
            this.Ticket_motaghazi1 = new HashSet<Ticket_motaghazi1>();
            this.Ticket_TimBarnamenervisi4 = new HashSet<Ticket_TimBarnamenervisi4>();
            this.UserBaleAccounts = new HashSet<UserBaleAccounts>();
            this.tbDocumentsAuthorizedUsers = new HashSet<tbDocumentsAuthorizedUsers>();
            this.tbDocumentsDefiOfDoctTitles_Users = new HashSet<tbDocumentsDefiOfDoctTitles_Users>();
            this.Contract_ceiling = new HashSet<Contract_ceiling>();
            this.dbtarifmahdodayt2 = new HashSet<dbtarifmahdodayt2>();
            this.dbtarifmahdodayt4 = new HashSet<dbtarifmahdodayt4>();
            this.dbtarifmahdodayt6 = new HashSet<dbtarifmahdodayt6>();
            this.gozaresh_1121_Fish = new HashSet<gozaresh_1121_Fish>();
            this.personalabzar = new HashSet<personalabzar>();
            this.tb_1118_Fish = new HashSet<tb_1118_Fish>();
            this.tbAddReduceMoadelkarkard = new HashSet<tbAddReduceMoadelkarkard>();
            this.tbcreat_countjob_Fish = new HashSet<tbcreat_countjob_Fish>();
            this.tbDetailFish = new HashSet<tbDetailFish>();
            this.tbgozaresh_1275_Fish = new HashSet<tbgozaresh_1275_Fish>();
            this.tbgozaresh_Hoshmand_Fish = new HashSet<tbgozaresh_Hoshmand_Fish>();
            this.tbHighLowMoalefeVal = new HashSet<tbHighLowMoalefeVal>();
            this.TBHoshdar2 = new HashSet<TBHoshdar2>();
            this.tbJaremehandpadash = new HashSet<tbJaremehandpadash>();
            this.tbkarkard_notsystem = new HashSet<tbkarkard_notsystem>();
            this.tbLink_name_usr = new HashSet<tbLink_name_usr>();
            this.tbLogFunctions = new HashSet<tbLogFunctions>();
            this.tbmadel_kar1 = new HashSet<tbmadel_kar1>();
            this.tbMaxkarkardMonth = new HashSet<tbMaxkarkardMonth>();
            this.tbMaxPayForMonth = new HashSet<tbMaxPayForMonth>();
            this.tbmoadel_kar2 = new HashSet<tbmoadel_kar2>();
            this.tbMoadelPadashJarimeAyab = new HashSet<tbMoadelPadashJarimeAyab>();
            this.tbMoalefeDastmozdiValueFromExcel = new HashSet<tbMoalefeDastmozdiValueFromExcel>();
            this.tbMoalefeValeFishTest = new HashSet<tbMoalefeValeFishTest>();
            this.tbMoalefeValue = new HashSet<tbMoalefeValue>();
            this.tbMoalefeValueFish = new HashSet<tbMoalefeValueFish>();
            this.tbMoalefeValuePishkhan = new HashSet<tbMoalefeValuePishkhan>();
            this.tbmoalfefishexcel = new HashSet<tbmoalfefishexcel>();
            this.tbmoalfehkasri = new HashSet<tbmoalfehkasri>();
            this.tbSaleryIsCalculated = new HashSet<tbSaleryIsCalculated>();
            this.tbSavedFunctions = new HashSet<tbSavedFunctions>();
            this.tbsaveSoratBasteh = new HashSet<tbsaveSoratBasteh>();
            this.vaziat_dastresi_Fish = new HashSet<vaziat_dastresi_Fish>();
            this.tbzarfiat_usr = new HashSet<tbzarfiat_usr>();
            this.tbReffrenceAcceptLevelUsers = new HashSet<tbReffrenceAcceptLevelUsers>();
            this.tbReffrenceSaveLevelUser = new HashSet<tbReffrenceSaveLevelUser>();
            this.tbCompanies = new HashSet<tbCompanies>();
            this.tbLink_UserAndAction = new HashSet<tbLink_UserAndAction>();
            this.tbRelUserJob = new HashSet<tbRelUserJob>();
            this.tbUser_link_BusinessSide = new HashSet<tbUser_link_BusinessSide>();
            this.Hosh1 = new HashSet<Hosh1>();
        }
    
        public int usr_ID { get; set; }
        public string usr_Name { get; set; }
        public string usr_Family { get; set; }
        public string usr_NationalCode { get; set; }
        public string usr_FatherName { get; set; }
        public int usr_Gender { get; set; }
        public Nullable<int> usr_MaritaIStatus { get; set; }
        public Nullable<System.DateTime> usr_DateOfBrith { get; set; }
        public Nullable<int> usr_PlaceOfBrith { get; set; }
        public Nullable<int> usr_PlaceOfIssue { get; set; }
        public Nullable<long> usr_PhoneNumber { get; set; }
        public Nullable<long> usr_PostalCode { get; set; }
        public string usr_Address { get; set; }
        public Nullable<int> usr_type { get; set; }
        public Nullable<long> usr_SHCode { get; set; }
        public Nullable<int> usr_Dutysystem { get; set; }
        public string usr_Email { get; set; }
        public string usr_Picture { get; set; }
        public Nullable<bool> usr_IsActive { get; set; }
        public string usr_Password { get; set; }
        public string usr_ActiveCode { get; set; }
        public Nullable<bool> usr_IsUser { get; set; }
        public Nullable<int> usr_ParentID { get; set; }
        public Nullable<long> usr_RegistrationNumber { get; set; }
        public Nullable<int> usr_SmsCode { get; set; }
        public Nullable<System.DateTime> usr_SmsCodeRecievedTime { get; set; }
        public Nullable<int> usr_PlaceOfRegister { get; set; }
        public Nullable<int> usr_Child_Allowance { get; set; }
        public Nullable<int> usr_Personal_ID { get; set; }
        public Nullable<int> usr_Degree { get; set; }
        public Nullable<int> usr_Grade { get; set; }
        public Nullable<int> usr_City_Dutysystem { get; set; }
        public Nullable<int> usr_All_Child_Allowance { get; set; }
        public Nullable<bool> usr_first_payment { get; set; }
        public Nullable<bool> usr_amani { get; set; }
        public Nullable<int> usr_typeshoghl { get; set; }
        public string usr_deyailjob { get; set; }
        public Nullable<int> usr_job { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link_User_And_Moalefe> Link_User_And_Moalefe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link_User_And_Peyman> Link_User_And_Peyman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbContractJobGroup> tbContractJobGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValue> tbEquipmentMoalefeValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipmentMoalefeValueReffrenceSave> tbEquipmentMoalefeValueReffrenceSave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEquipments> tbEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbFucntionExcel> tbFucntionExcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmarahesabt4> tbmarahesabt4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserContracts> tbUserContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbvaziat_mahdodayt> tbvaziat_mahdodayt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi1> arzyzbi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi2_soal> arzyzbi2_soal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi3_gozeneh> arzyzbi3_gozeneh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi4_link> arzyzbi4_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi5_time> arzyzbi5_time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi6_value> arzyzbi6_value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi7_value_usr> arzyzbi7_value_usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arzyzbi8_edit> arzyzbi8_edit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaleLinkRequests> BaleLinkRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<closed_time_estedad> closed_time_estedad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlVersions> ControlVersions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Create_linkmamorjob_4> Create_linkmamorjob_4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadCheack4> dbAsnadCheack4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadcratasnad> dbAsnadcratasnad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadDastehband2> dbAsnadDastehband2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnadsalvorodi> dbAsnadsalvorodi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbAsnaduplaodfil3> dbAsnaduplaodfil3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbdashbord1> dbdashbord1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbdashbordmamor> dbdashbordmamor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dberganametanble2_2> dberganametanble2_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergapilike> dbergapilike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergha2> dbergha2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergha6> dbergha6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharel_4> dbergharel_4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharel2_3> dbergharel2_3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharel4_5> dbergharel4_5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelicratgroup_8> dbergharelicratgroup_8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelicratgrouprel11> dbergharelicratgrouprel11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelicratgrouprel8_9> dbergharelicratgrouprel8_9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelicreatejob13> dbergharelicreatejob13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelimsertfk1_7> dbergharelimsertfk1_7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbergharelinsert_6> dbergharelinsert_6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dberja> dberja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbGIS_USR> dbGIS_USR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbGIS_USR_after> dbGIS_USR_after { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dblog> dblog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbmovazafisabt> dbmovazafisabt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbRelatinafrad> dbRelatinafrad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbrelatinperson> dbrelatinperson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbsathdastressi4> dbsathdastressi4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtarifmovazaf> dbtarifmovazaf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtarifvazifehasli> dbtarifvazifehasli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbvaziathozor> dbvaziathozor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erja_like> erja_like { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erja_sabt_usr> erja_sabt_usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estedad_khodro> estedad_khodro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstedadNiroEnsani> EstedadNiroEnsani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialDocuments> FinancialDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_1> madarek_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_linkcheack_2> madarek_linkcheack_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_linkesabt_3> madarek_linkesabt_3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_sabtdoreh_4> madarek_sabtdoreh_4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<madarek_vaziatdoreh_5> madarek_vaziatdoreh_5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NatigeEshterakBala50> NatigeEshterakBala50 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Khodro> Table_Khodro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Khodro> Table_Khodro1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Khodro> Table_Khodro2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Khodro> Table_Khodro3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAdamAdam> tbAdamAdam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAdamAdam> tbAdamAdam1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAdamShahr> tbAdamShahr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbcount_car> tbcount_car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocuments> tbDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbExcelDocument> tbExcelDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbgozaresh_1258> tbgozaresh_1258 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHoshdar> tbHoshdar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbinstallments> tbinstallments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbperson> tbperson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSabtEstedadKhodro> tbSabtEstedadKhodro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsherkatpyam> tbsherkatpyam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsherkatpyam> tbsherkatpyam1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSuggestion> tbSuggestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSuggestion_Admin> tbSuggestion_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbvalue_frml> tbvalue_frml { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_motaghazi1> Ticket_motaghazi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_TimBarnamenervisi4> Ticket_TimBarnamenervisi4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBaleAccounts> UserBaleAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocumentsAuthorizedUsers> tbDocumentsAuthorizedUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDocumentsDefiOfDoctTitles_Users> tbDocumentsDefiOfDoctTitles_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_ceiling> Contract_ceiling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtarifmahdodayt2> dbtarifmahdodayt2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtarifmahdodayt4> dbtarifmahdodayt4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbtarifmahdodayt6> dbtarifmahdodayt6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gozaresh_1121_Fish> gozaresh_1121_Fish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personalabzar> personalabzar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_1118_Fish> tb_1118_Fish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAddReduceMoadelkarkard> tbAddReduceMoadelkarkard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbcreat_countjob_Fish> tbcreat_countjob_Fish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetailFish> tbDetailFish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbgozaresh_1275_Fish> tbgozaresh_1275_Fish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbgozaresh_Hoshmand_Fish> tbgozaresh_Hoshmand_Fish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHighLowMoalefeVal> tbHighLowMoalefeVal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBHoshdar2> TBHoshdar2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbJaremehandpadash> tbJaremehandpadash { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbkarkard_notsystem> tbkarkard_notsystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLink_name_usr> tbLink_name_usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLogFunctions> tbLogFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmadel_kar1> tbmadel_kar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMaxkarkardMonth> tbMaxkarkardMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMaxPayForMonth> tbMaxPayForMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoadel_kar2> tbmoadel_kar2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoadelPadashJarimeAyab> tbMoadelPadashJarimeAyab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeDastmozdiValueFromExcel> tbMoalefeDastmozdiValueFromExcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValeFishTest> tbMoalefeValeFishTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValue> tbMoalefeValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValueFish> tbMoalefeValueFish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMoalefeValuePishkhan> tbMoalefeValuePishkhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoalfefishexcel> tbmoalfefishexcel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbmoalfehkasri> tbmoalfehkasri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSaleryIsCalculated> tbSaleryIsCalculated { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSavedFunctions> tbSavedFunctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbsaveSoratBasteh> tbsaveSoratBasteh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaziat_dastresi_Fish> vaziat_dastresi_Fish { get; set; }
        public virtual tbdetailjob tbdetailjob { get; set; }
        public virtual tbjob tbjob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbzarfiat_usr> tbzarfiat_usr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceAcceptLevelUsers> tbReffrenceAcceptLevelUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReffrenceSaveLevelUser> tbReffrenceSaveLevelUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCompanies> tbCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLink_UserAndAction> tbLink_UserAndAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRelUserJob> tbRelUserJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUser_link_BusinessSide> tbUser_link_BusinessSide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosh1> Hosh1 { get; set; }
    }
}
