//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserContracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUserContracts()
        {
            this.tbUserContractsAndMoalefeGhararDadi = new HashSet<tbUserContractsAndMoalefeGhararDadi>();
            this.tbUserContractsAndMoalefeGhararDadi1 = new HashSet<tbUserContractsAndMoalefeGhararDadi1>();
        }
    
        public int usc_ID { get; set; }
        public string usc_ContractNumber { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public Nullable<int> usc_JobCode { get; set; }
        public Nullable<int> FK_JobGroup { get; set; }
        public string usc_Jobtitle { get; set; }
        public Nullable<bool> usc_TypeOfContract { get; set; }
        public Nullable<int> FK_KarfarmaID { get; set; }
        public Nullable<System.DateTime> usc_StartTime { get; set; }
        public Nullable<System.DateTime> usc_EndTime { get; set; }
        public string usc_FileName { get; set; }
        public string usc_FileSystemName { get; set; }
        public Nullable<int> usc_TedadSalSanavat { get; set; }
        public string jobgroup_ValueMozdGroup { get; set; }
        public string jobgroup_ValueSanavat { get; set; }
        public string jobgroup_KharoBar { get; set; }
        public string jobgroup_HagheMaskan { get; set; }
        public string jobgroup_HagheOlad { get; set; }
        public Nullable<int> FK_KarfarmaAsli { get; set; }
        public string jobgroup_MozdSayer { get; set; }
        public Nullable<int> FirstMonthFish { get; set; }
        public Nullable<int> FK_job { get; set; }
        public string Sharhvazayf { get; set; }
        public string sharh { get; set; }
        public string shraytfasgh { get; set; }
    
        public virtual tbCompanies tbCompanies { get; set; }
        public virtual tbCompanies tbCompanies1 { get; set; }
        public virtual tbjob tbjob { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserContractsAndMoalefeGhararDadi> tbUserContractsAndMoalefeGhararDadi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbUserContractsAndMoalefeGhararDadi1> tbUserContractsAndMoalefeGhararDadi1 { get; set; }
    }
}
