//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser_link_BusinessSide
    {
        public int ulp_Id { get; set; }
        public Nullable<int> FK_up_ID { get; set; }
        public Nullable<int> FK_u_ID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual tbBusinessSide tbBusinessSide { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
