//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbvalue_frml
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> FK_moalf { get; set; }
        public Nullable<int> FK_pymn { get; set; }
        public Nullable<double> valu_double { get; set; }
        public Nullable<long> value_long { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> numbr_sorat { get; set; }
        public Nullable<long> FK_nameFormol { get; set; }
        public Nullable<long> shomareh { get; set; }
        public string sharh { get; set; }
        public Nullable<System.DateTime> Datatime { get; set; }
        public Nullable<int> usr_sabt { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbcreat_NameFrml tbcreat_NameFrml { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
