//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbvaziat_mahdodayt
    {
        public long ID { get; set; }
        public Nullable<int> FK_usr { get; set; }
        public Nullable<int> pymn { get; set; }
        public Nullable<int> vaziat { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
        public virtual tbCities tbCities { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
