//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbzarfiat_mantaghe
    {
        public long ID { get; set; }
        public Nullable<int> mantagheh1 { get; set; }
        public Nullable<int> mantagheh2 { get; set; }
        public Nullable<int> mantagheh3 { get; set; }
        public Nullable<int> mantagheh4 { get; set; }
        public Nullable<int> mantagheh5 { get; set; }
        public Nullable<int> mantagheh6 { get; set; }
        public Nullable<int> mantagheh7 { get; set; }
        public string city_name { get; set; }
        public Nullable<int> mantagheh8 { get; set; }
        public Nullable<int> mantagheh9 { get; set; }
        public Nullable<long> mablagh { get; set; }
        public Nullable<decimal> mablagh_fl { get; set; }
        public Nullable<int> fall { get; set; }
        public string city_name2 { get; set; }
        public Nullable<decimal> zarib { get; set; }
    }
}
