//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_TimBarnamenervisi4
    {
        public long ID { get; set; }
        public Nullable<long> Fk_Ticket_motaghazi1 { get; set; }
        public Nullable<long> Fk_Ticket_Barnamerizi3 { get; set; }
        public Nullable<bool> AnjamShode { get; set; }
        public Nullable<bool> DarDastorKar { get; set; }
        public string EslahFarayand { get; set; }
        public Nullable<int> UserSabt { get; set; }
        public Nullable<System.DateTime> TimeSabt { get; set; }
    
        public virtual Ticket_Barnamerizi3 Ticket_Barnamerizi3 { get; set; }
        public virtual Ticket_motaghazi1 Ticket_motaghazi1 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
