//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_motaghazi1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket_motaghazi1()
        {
            this.Ticket_Barnamerizi3 = new HashSet<Ticket_Barnamerizi3>();
            this.Ticket_IT_2 = new HashSet<Ticket_IT_2>();
            this.Ticket_TimBarnamenervisi4 = new HashSet<Ticket_TimBarnamenervisi4>();
        }
    
        public long ID { get; set; }
        public Nullable<int> OnvanDarkhast { get; set; }
        public string Sharh { get; set; }
        public string ElatYaRishe { get; set; }
        public string BehbodKarayi { get; set; }
        public string KomakBeSayerBakhshHa { get; set; }
        public Nullable<int> Olaviat { get; set; }
        public string ZamanAnjam { get; set; }
        public string Farayand { get; set; }
        public Nullable<int> UserSabt { get; set; }
        public Nullable<System.DateTime> TimeSabt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Barnamerizi3> Ticket_Barnamerizi3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_IT_2> Ticket_IT_2 { get; set; }
        public virtual tbUsers tbUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_TimBarnamenervisi4> Ticket_TimBarnamenervisi4 { get; set; }
    }
}
