//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Barnamerizi3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket_Barnamerizi3()
        {
            this.Ticket_TimBarnamenervisi4 = new HashSet<Ticket_TimBarnamenervisi4>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FK_Ticket_Motaghazi1 { get; set; }
        public Nullable<long> FK_Ticket_it_2 { get; set; }
        public string Olaviat { get; set; }
        public string ZaroratAnjam { get; set; }
        public string SayerTozihat { get; set; }
        public Nullable<int> UserSabt { get; set; }
        public Nullable<System.DateTime> TimeSabt { get; set; }
        public Nullable<int> Olaviat2 { get; set; }
    
        public virtual Ticket_IT_2 Ticket_IT_2 { get; set; }
        public virtual Ticket_motaghazi1 Ticket_motaghazi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_TimBarnamenervisi4> Ticket_TimBarnamenervisi4 { get; set; }
    }
}
