//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_IT_2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket_IT_2()
        {
            this.Ticket_Barnamerizi3 = new HashSet<Ticket_Barnamerizi3>();
        }
    
        public long ID { get; set; }
        public Nullable<long> Fk_Darkhast_Ticket_motaghazi1 { get; set; }
        public Nullable<int> Anjamdahande { get; set; }
        public string zamanKar { get; set; }
        public string AfradAnjamdahande { get; set; }
        public string Olaviat { get; set; }
        public string Hazine { get; set; }
        public string BarasiFarayand { get; set; }
        public string SayerToziihat { get; set; }
        public Nullable<int> UserSabt { get; set; }
        public Nullable<System.DateTime> TimeSabt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Barnamerizi3> Ticket_Barnamerizi3 { get; set; }
        public virtual Ticket_motaghazi1 Ticket_motaghazi1 { get; set; }
    }
}
