//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBaleAccounts
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public long BaleChatId { get; set; }
        public Nullable<long> BaleUserId { get; set; }
        public string BaleUsername { get; set; }
        public string BaleFirstName { get; set; }
        public string BaleLastName { get; set; }
        public bool IsActive { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<System.DateTime> ConnectedAt { get; set; }
        public Nullable<System.DateTime> LastInteractionAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
