//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuunicPriorityResult2
    {
        public long ID { get; set; }
        public string valuunic { get; set; }
        public string city { get; set; }
        public string makaan { get; set; }
        public string nametarefeh { get; set; }
        public string noeshtrak { get; set; }
        public string mahdodeh { get; set; }
        public string shomaremobile { get; set; }
        public string parvandeh { get; set; }
        public string eshterak { get; set; }
        public string roz { get; set; }
        public string shenasehpardaght { get; set; }
        public int P1 { get; set; }
        public int P2 { get; set; }
        public int P3 { get; set; }
        public int P4 { get; set; }
        public decimal P5 { get; set; }
        public long SortRank { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> yaer { get; set; }
        public Nullable<int> month { get; set; }
        public string item1 { get; set; }
        public string item2 { get; set; }
        public string item3 { get; set; }
        public string item4 { get; set; }
    }
}
