//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaabWebProject.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaziatsoratvaziat
    {
        public long ID { get; set; }
        public Nullable<bool> vaziat { get; set; }
        public Nullable<int> FK_pymn { get; set; }
        public Nullable<int> FK_Moalfeh { get; set; }
    
        public virtual tbContractMoalefeDastmozdi tbContractMoalefeDastmozdi { get; set; }
        public virtual tbPeymanContracts tbPeymanContracts { get; set; }
    }
}
