//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paymentReceipt.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFish
    {
        public int fsh_ID { get; set; }
        public Nullable<int> FK_User { get; set; }
        public Nullable<System.DateTime> fsh_DateTime { get; set; }
    }
}
