//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paymentReceipt.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKarkard
    {
        public int krkrd_ID { get; set; }
        public Nullable<int> FK_ProjectID { get; set; }
        public string krkrd_Title { get; set; }
        public Nullable<int> krkrd_Duration { get; set; }
        public Nullable<double> krkrd_StandardValue { get; set; }
    }
}
