//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paymentReceipt.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTax
    {
        public int tx_ID { get; set; }
        public Nullable<int> tx_Step { get; set; }
        public Nullable<double> tx_MaximumYearSalary { get; set; }
        public Nullable<double> tx_MaximumMonthSalary { get; set; }
        public Nullable<double> tx_TaxRatio { get; set; }
        public Nullable<double> tx_YearTaxValue { get; set; }
        public Nullable<double> tx_MonthTaxValue { get; set; }
    }
}
